name = "synthetix-omnibus"
version = "3.0.0-alpha.7"
description = "Includes the full synthetix system with configurations applied"

include = [
    "tomls/core.toml",
    #"tomls/collaterals/snx.toml",
    "tomls/collaterals/weth.toml",
    "tomls/pools/spartan-council.toml",
     
    # to be enabled when ccip is a thing
    #"tomls/ccip.toml"
]