name = "synthetix-omnibus"
version = "3.0.0-alpha.8"
description = "Includes the full synthetix system with configurations applied"

[setting.owner]
defaultValue = "0x48914229deDd5A9922f44441ffCCfC2Cb7856Ee9"

[setting.weth_address]
defaultValue = "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6"

[setting.weth_aggregator_address]
defaultValue = "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"

[setting.snx_address]
defaultValue = "0x51f44ca59b867E005e48FA573Cb8df83FC7f7597"

[setting.snx_aggregator_address]
defaultValue = "0x48731cF7e84dc94C5f84577882c14Be11a5B7456"

# Move to a draft PR with ccip.draft.toml ?
# [setting.ccip_send_address]
# defaultValue = "0xA189971a2c5AcA0DFC5Ee7a2C44a2Ae27b3CF389"
# 
# [setting.ccip_recv_address]
# defaultValue = "0xb78d314d32EB4B01C459EDE0774cc3b6AF244Dd7"
# 
# [setting.ccip_token_pool_address]
# defaultValue = "0x1fce171011B16F3b0D16198e3F59FD72c091f43B"

[setting.minimum_liquidity_ratio]
defaultValue = "<%= parseEther('200') %>"

include = [
    "tomls/core.toml",
    "tomls/collaterals/snx.toml",
    "tomls/collaterals/weth.toml",
    "tomls/pools/spartan-council.toml",
]