[invoke.CoreProxy_configureCollateral_tBTC]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"  # "args" see below in the multiline block

[[invoke.CoreProxy_configureCollateral_tBTC.args]]
tokenAddress = "<%= settings.tBTC_address %>"
oracleNodeId = "<%= extras.tBTC_oracle_id %>"
issuanceRatioD18 = "<%= parseEther('2') %>"
liquidationRatioD18 = "<%= parseEther('1.1') %>"
liquidationRewardD18 = "<%= parseEther('0.5') %>"
minDelegationD18 = "<%= parseEther('0.5') %>"
depositingEnabled = false
