[var.perps_bch_market_settings]
bch_perps_market_id = "2600"
bch_perps_market_skew_scale = "<%= parseEther(String(84_375)) %>"
bch_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
bch_perps_maker_fee_ratio = "<%= parseEther('0') %>"
bch_perps_taker_fee_ratio = "<%= parseEther('0.0005') %>"
bch_perps_max_market_size = "<%= parseEther(String(15_000)) %>"
bch_perps_max_market_value = "<%= parseEther(String(5_000_000)) %>"
bch_perps_initial_margin_ratio = "<%= parseEther('1.1') %>"
bch_perps_maintenance_margin_scalar = "<%= parseEther('0.31') %>"
bch_perps_minimum_initial_margin_ratio = "<%= parseEther('0.05') %>"
bch_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
bch_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
bch_perps_max_seconds_in_liquidation_window = "30"
bch_perps_minimum_position_margin = "<%= parseEther('50') %>"
bch_perps_locked_oi_ratio = "<%= parseEther('0.50') %>"
bch_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
bch_perps_endorsed_liquidator = "0x95A61Fa7454CA5f6A3CE01724e306Cd14a22D306"

[invoke.createBchPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.bch_perps_market_id %>", "Bitcoin Cash", "BCH"]

[invoke.setPerpsPriceBch]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.bch_perps_market_id %>",
    "<%= extras.bch_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsBchSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.bch_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.bch_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.bch_pyth_settlement_strategy.arg = 2
[invoke.setPerpsBchSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.bch_perps_market_id %>",
    "<%= extras.bch_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_bch %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsBchFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.bch_perps_market_id %>",
    "<%= settings.bch_perps_market_skew_scale %>",
    "<%= settings.bch_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsBchOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.bch_perps_market_id %>",
    "<%= settings.bch_perps_maker_fee_ratio %>",
    "<%= settings.bch_perps_taker_fee_ratio %>",
]

[invoke.setPerpsBchMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.bch_perps_market_id %>", "<%= settings.bch_perps_max_market_size %>"]

[invoke.setPerpsBchMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.bch_perps_market_id %>", "<%= settings.bch_perps_max_market_value %>"]

[invoke.setPerpsBchMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.bch_perps_market_id %>",
    "<%= settings.bch_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.bch_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.bch_perps_max_liquidation_pd %>",
    "<%= settings.bch_perps_endorsed_liquidator %>",
]

[invoke.setPerpsBchLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.bch_perps_market_id %>",
    "<%= settings.bch_perps_initial_margin_ratio %>",
    "<%= settings.bch_perps_minimum_initial_margin_ratio %>",
    "<%= settings.bch_perps_maintenance_margin_scalar %>",
    "<%= settings.bch_perps_flag_reward_ratio_d18 %>",
    "<%= settings.bch_perps_minimum_position_margin %>",
]

[invoke.setPerpsBchLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.bch_perps_market_id %>", "<%= settings.bch_perps_locked_oi_ratio %>"]
