[var.perps_bonk_market_settings]
bonk_perps_market_id = "4000"
bonk_perps_market_skew_scale = "<%= parseEther(String(1_600_000_000_000)) %>"
bonk_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
bonk_perps_maker_fee_ratio = "<%= parseEther('0.000000') %>"
bonk_perps_taker_fee_ratio = "<%= parseEther('0.000500') %>"
bonk_perps_max_market_size = "<%= parseEther(String(135_525_228_000)) %>"
bonk_perps_max_market_value = "<%= parseEther(String(2_000_000)) %>"
bonk_perps_initial_margin_ratio = "<%= parseEther('2.55') %>"
bonk_perps_maintenance_margin_scalar = "<%= parseEther('0.37') %>"
bonk_perps_minimum_initial_margin_ratio = "<%= parseEther('0.05') %>"
bonk_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
bonk_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
bonk_perps_max_seconds_in_liquidation_window = "30"
bonk_perps_minimum_position_margin = "<%= parseEther('50') %>"
bonk_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
bonk_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
bonk_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createBonkPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.bonk_perps_market_id %>", "Bonk", "BONK"]

[invoke.setPerpsPriceBonk]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.bonk_perps_market_id %>",
    "<%= extras.bonk_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsBonkSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.bonk_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.bonk_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.bonk_pyth_settlement_strategy.arg = 2
[invoke.setPerpsBonkSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.bonk_perps_market_id %>",
    "<%= extras.bonk_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_bonk %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsBonkFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.bonk_perps_market_id %>",
    "<%= settings.bonk_perps_market_skew_scale %>",
    "<%= settings.bonk_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsBonkOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.bonk_perps_market_id %>",
    "<%= settings.bonk_perps_maker_fee_ratio %>",
    "<%= settings.bonk_perps_taker_fee_ratio %>",
]

[invoke.setPerpsBonkMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.bonk_perps_market_id %>", "<%= settings.bonk_perps_max_market_size %>"]

[invoke.setPerpsBonkMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.bonk_perps_market_id %>", "<%= settings.bonk_perps_max_market_value %>"]

[invoke.setPerpsBonkMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.bonk_perps_market_id %>",
    "<%= settings.bonk_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.bonk_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.bonk_perps_max_liquidation_pd %>",
    "<%= settings.bonk_perps_endorsed_liquidator %>",
]

[invoke.setPerpsBonkLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.bonk_perps_market_id %>",
    "<%= settings.bonk_perps_initial_margin_ratio %>",
    "<%= settings.bonk_perps_minimum_initial_margin_ratio %>",
    "<%= settings.bonk_perps_maintenance_margin_scalar %>",
    "<%= settings.bonk_perps_flag_reward_ratio_d18 %>",
    "<%= settings.bonk_perps_minimum_position_margin %>",
]

[invoke.setPerpsBonkLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.bonk_perps_market_id %>", "<%= settings.bonk_perps_locked_oi_ratio %>"]
