[var.perps_icp_market_settings]
icp_perps_market_id = "5400"
icp_perps_market_skew_scale = "<%= parseEther(String(3_000_000)) %>"
icp_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
icp_perps_maker_fee_ratio = "<%= parseEther('0.000000') %>"
icp_perps_taker_fee_ratio = "<%= parseEther('0.000500') %>"
icp_perps_max_market_size = "<%= parseEther(String(91_100)) %>"
icp_perps_max_market_value = "<%= parseEther(String(500_000)) %>"
icp_perps_initial_margin_ratio = "<%= parseEther('1.86') %>"
icp_perps_maintenance_margin_scalar = "<%= parseEther('0.44') %>"
icp_perps_minimum_initial_margin_ratio = "<%= parseEther('0.05') %>"
icp_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
icp_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
icp_perps_max_seconds_in_liquidation_window = "30"
icp_perps_minimum_position_margin = "<%= parseEther('50') %>"
icp_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
icp_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
icp_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createIcpPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.icp_perps_market_id %>", "Internet Computer", "ICP"]

[invoke.setPerpsPriceIcp]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.icp_perps_market_id %>",
    "<%= extras.icp_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsIcpSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.icp_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.icp_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.icp_pyth_settlement_strategy.arg = 2
[invoke.setPerpsIcpSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.icp_perps_market_id %>",
    "<%= extras.icp_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_icp %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsIcpFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.icp_perps_market_id %>",
    "<%= settings.icp_perps_market_skew_scale %>",
    "<%= settings.icp_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsIcpOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.icp_perps_market_id %>",
    "<%= settings.icp_perps_maker_fee_ratio %>",
    "<%= settings.icp_perps_taker_fee_ratio %>",
]

[invoke.setPerpsIcpMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.icp_perps_market_id %>", "<%= settings.icp_perps_max_market_size %>"]

[invoke.setPerpsIcpMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.icp_perps_market_id %>", "<%= settings.icp_perps_max_market_value %>"]

[invoke.setPerpsIcpMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.icp_perps_market_id %>",
    "<%= settings.icp_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.icp_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.icp_perps_max_liquidation_pd %>",
    "<%= settings.icp_perps_endorsed_liquidator %>",
]

[invoke.setPerpsIcpLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.icp_perps_market_id %>",
    "<%= settings.icp_perps_initial_margin_ratio %>",
    "<%= settings.icp_perps_minimum_initial_margin_ratio %>",
    "<%= settings.icp_perps_maintenance_margin_scalar %>",
    "<%= settings.icp_perps_flag_reward_ratio_d18 %>",
    "<%= settings.icp_perps_minimum_position_margin %>",
]

[invoke.setPerpsIcpLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.icp_perps_market_id %>", "<%= settings.icp_perps_locked_oi_ratio %>"]
