[var.perps_io_market_settings]
io_perps_market_id = "8100"
io_perps_market_skew_scale = "<%= parseEther(String(6_000_000)) %>"
io_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
io_perps_maker_fee_ratio = "<%= parseEther('0.000000') %>"
io_perps_taker_fee_ratio = "<%= parseEther('0.000500') %>"
io_perps_max_market_size = "<%= parseEther(String(477_550)) %>"
io_perps_max_market_value = "<%= parseEther(String(1_000_000)) %>"
io_perps_initial_margin_ratio = "<%= parseEther('0.694') %>"
io_perps_maintenance_margin_scalar = "<%= parseEther('0.334') %>"
io_perps_minimum_initial_margin_ratio = "<%= parseEther('0.05') %>"
io_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
io_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
io_perps_max_seconds_in_liquidation_window = "30"
io_perps_minimum_position_margin = "<%= parseEther('50') %>"
io_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
io_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
io_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createIoPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.io_perps_market_id %>", "io.net", "IO"]

[invoke.setPerpsPriceIo]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.io_perps_market_id %>",
    "<%= extras.io_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsIoSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.io_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.io_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.io_pyth_settlement_strategy.arg = 2
[invoke.setPerpsIoSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.io_perps_market_id %>",
    "<%= extras.io_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_io %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsIoFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.io_perps_market_id %>",
    "<%= settings.io_perps_market_skew_scale %>",
    "<%= settings.io_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsIoOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.io_perps_market_id %>",
    "<%= settings.io_perps_maker_fee_ratio %>",
    "<%= settings.io_perps_taker_fee_ratio %>",
]

[invoke.setPerpsIoMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.io_perps_market_id %>", "<%= settings.io_perps_max_market_size %>"]

[invoke.setPerpsIoMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.io_perps_market_id %>", "<%= settings.io_perps_max_market_value %>"]

[invoke.setPerpsIoMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.io_perps_market_id %>",
    "<%= settings.io_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.io_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.io_perps_max_liquidation_pd %>",
    "<%= settings.io_perps_endorsed_liquidator %>",
]

[invoke.setPerpsIoLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.io_perps_market_id %>",
    "<%= settings.io_perps_initial_margin_ratio %>",
    "<%= settings.io_perps_minimum_initial_margin_ratio %>",
    "<%= settings.io_perps_maintenance_margin_scalar %>",
    "<%= settings.io_perps_flag_reward_ratio_d18 %>",
    "<%= settings.io_perps_minimum_position_margin %>",
]

[invoke.setPerpsIoLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.io_perps_market_id %>", "<%= settings.io_perps_locked_oi_ratio %>"]
