[var.perps_moodeng_market_settings]
moodeng_perps_market_id = "8700"
moodeng_perps_market_skew_scale = "<%= parseEther(String(50_000_000)) %>"
moodeng_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
moodeng_perps_maker_fee_ratio = "<%= parseEther('0.000000') %>"
moodeng_perps_taker_fee_ratio = "<%= parseEther('0.000500') %>"
moodeng_perps_max_market_size = "<%= parseEther(String(34_000_000)) %>"
moodeng_perps_max_market_value = "<%= parseEther(String(3_000_000)) %>"
moodeng_perps_initial_margin_ratio = "<%= parseEther('1.588') %>"
moodeng_perps_maintenance_margin_scalar = "<%= parseEther('0.317') %>"
moodeng_perps_minimum_initial_margin_ratio = "<%= parseEther('0.05') %>"
moodeng_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
moodeng_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
moodeng_perps_max_seconds_in_liquidation_window = "30"
moodeng_perps_minimum_position_margin = "<%= parseEther('50') %>"
moodeng_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
moodeng_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
moodeng_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createMoodengPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.moodeng_perps_market_id %>", "Moo Deng", "MOODENG"]

[invoke.setPerpsPriceMoodeng]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.moodeng_perps_market_id %>",
    "<%= extras.moodeng_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsMoodengSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.moodeng_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.moodeng_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.moodeng_pyth_settlement_strategy.arg = 2
[invoke.setPerpsMoodengSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.moodeng_perps_market_id %>",
    "<%= extras.moodeng_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_moodeng %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsMoodengFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.moodeng_perps_market_id %>",
    "<%= settings.moodeng_perps_market_skew_scale %>",
    "<%= settings.moodeng_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsMoodengOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.moodeng_perps_market_id %>",
    "<%= settings.moodeng_perps_maker_fee_ratio %>",
    "<%= settings.moodeng_perps_taker_fee_ratio %>",
]

[invoke.setPerpsMoodengMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.moodeng_perps_market_id %>", "<%= settings.moodeng_perps_max_market_size %>"]

[invoke.setPerpsMoodengMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.moodeng_perps_market_id %>", "<%= settings.moodeng_perps_max_market_value %>"]

[invoke.setPerpsMoodengMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.moodeng_perps_market_id %>",
    "<%= settings.moodeng_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.moodeng_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.moodeng_perps_max_liquidation_pd %>",
    "<%= settings.moodeng_perps_endorsed_liquidator %>",
]

[invoke.setPerpsMoodengLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.moodeng_perps_market_id %>",
    "<%= settings.moodeng_perps_initial_margin_ratio %>",
    "<%= settings.moodeng_perps_minimum_initial_margin_ratio %>",
    "<%= settings.moodeng_perps_maintenance_margin_scalar %>",
    "<%= settings.moodeng_perps_flag_reward_ratio_d18 %>",
    "<%= settings.moodeng_perps_minimum_position_margin %>",
]

[invoke.setPerpsMoodengLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.moodeng_perps_market_id %>", "<%= settings.moodeng_perps_locked_oi_ratio %>"]
