[setting.usdc_issuance_ratio]
defaultValue = "<%= parseEther('1.2') %>"

[setting.usdc_liquidation_ratio]
defaultValue = "<%= parseEther('1.05') %>"

[setting.usdc_liquidation_reward]
defaultValue = "<%= '1000000' %>"

[setting.usdc_min_delegation]
defaultValue = "<%= '100000000' %>"

[invoke.CoreProxy_configureCollateral_usdc]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"  # "args" see below in the multiline block

[[invoke.CoreProxy_configureCollateral_usdc.args]]
tokenAddress = "<%= settings.usdc_address %>"
oracleNodeId = "<%= extras.usdc_oracle_id %>"
issuanceRatioD18 = "<%= settings.usdc_issuance_ratio %>"
liquidationRatioD18 = "<%= settings.usdc_liquidation_ratio %>"
liquidationRewardD18 = "<%= settings.usdc_liquidation_reward %>"
minDelegationD18 = "<%= settings.usdc_min_delegation %>"
depositingEnabled = true
