[var.weth_spot_settings]
synth_weth_max_collateral_amount = "<%= parseEther(String(1_750)) %>"
synth_weth_skew_scale = "<%= parseEther(String(350_000)) %>"

[invoke.SpotMarketProxy_createSynth_weth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "owner"
func = "createSynth"
args = ["Synthetic Wrapped ETH", "sWETH", "<%= settings.owner %>"]
extra.synth_weth_market_id.event = "SynthRegistered"
extra.synth_weth_market_id.arg = 0
extra.synth_weth_token_address.event = "SynthRegistered"
extra.synth_weth_token_address.arg = 1

[invoke.SpotMarketProxy_updatePriceData_weth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_weth_market_id %>"]
func = "updatePriceData"
args = [
    "<%= extras.synth_weth_market_id %>",
    "<%= extras.eth_oracle_id %>",
    "<%= extras.eth_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.CoreProxy_configureMaximumMarketCollateral_weth]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= extras.synth_weth_market_id %>",
    "<%= settings.weth_address %>",
    "<%= settings.synth_weth_max_collateral_amount %>",
]

[invoke.SpotMarketProxy_setMarketSkewScale_weth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_weth_market_id %>"]
func = "setMarketSkewScale"
args = ["<%= extras.synth_weth_market_id %>", "<%= settings.synth_weth_skew_scale %>"]

[invoke.SpotMarketProxy_setWrapper_weth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_weth_market_id %>"]
func = "setWrapper"
args = [
    "<%= extras.synth_weth_market_id %>",
    "<%= settings.weth_address %>",
    "<%= settings.synth_weth_max_collateral_amount %>",
]

# NOTE set disabled = true to addSettlementStrategy call before initial mainnet deployment
[invoke.SpotMarketProxy_addSettlementStrategy_weth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_weth_market_id %>"]
func = "addSettlementStrategy"
args = [
    "<%= extras.synth_weth_market_id %>",
    { strategyType = "1", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", url = "", settlementReward = 0, minimumUsdExchangeAmount = "0", maxRoundingLoss = "1", priceDeviationTolerance = "0", disabled = false },
]
extra.synth_weth_settlement_strategy_id.event = "SettlementStrategyAdded"
extra.synth_weth_settlement_strategy_id.arg = 1

[invoke.SpotMarketProxy_setSettlementStrategy_weth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_weth_market_id %>"]
func = "setSettlementStrategy"
args = [
    "<%= extras.synth_weth_market_id %>",
    "<%= extras.synth_weth_settlement_strategy_id %>",
    { strategyType = "1", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_weth %>", url = "<%= settings.pyth_feed_url %>", settlementReward = "<%= settings.settlement_reward %>", minimumUsdExchangeAmount = "<%= settings.settlement_minimum_usd_exchange_amount %>", maxRoundingLoss = "<%= settings.settlement_max_rounding_loss %>", priceDeviationTolerance = "<%= settings.price_deviation_tolerance %>", disabled = true },
]

[invoke.SpotMarketProxy_setAtomicFixedFee_weth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_weth_market_id %>"]
func = "setAtomicFixedFee"
args = ["<%= extras.synth_weth_market_id %>", "<%= parseEther(String(0.3)) %>"]

[invoke.SpotMarketProxy_setCollateralLeverage_weth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_weth_market_id %>"]
func = "setCollateralLeverage"
args = ["<%= extras.synth_weth_market_id %>", "<%= parseEther('10') %>"]
