[setting.pythAdaFeedId]
defaultValue = "0x2a01deaec9e51a579277b34b122399984d0bbf57e2458a7e42fecd2829867a0d"

[setting.perpsAdaMarketId]
defaultValue = "3400"

[setting.perpsAdaSkewScale]
defaultValue = "<%=String(150_000_000) %>"

[setting.perpsAdaMaxFundingVelocity]
defaultValue = "36"

[setting.perpsAdaMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsAdaTakerFeeRatio]
defaultValue = "0.001"

[setting.perpsAdaMaxMarketSize]
defaultValue = "<%=String(499_984) %>"

[setting.perpsAdaMaxMarketValue]
defaultValue = "<%=String(100_000) %>"

[setting.perpsAdaInitialMarginRatio]
defaultValue = "4.35"

[setting.perpsAdaMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsAdaMaintenanceMarginScalar]
defaultValue = "0.33"

[setting.perpsAdaFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsAdaMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsAdaMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsAdaMinimumPositionMargin]
defaultValue = "50"

[setting.perpsAdaLockedOiRatio]
defaultValue = "0.5"

[setting.perpsAdaSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsAdaMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsAdaEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
