[setting.pythBalFeedId]
defaultValue = "0x07ad7b4a7662d19a6bc675f6b467172d2f3947fa653ca97555a9b20236406628"

[setting.perpsBalMarketId]
defaultValue = "3900"

[setting.perpsBalSkewScale]
defaultValue = "<%=String(1_125_000) %>"

[setting.perpsBalMaxFundingVelocity]
defaultValue = "36"

[setting.perpsBalMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsBalTakerFeeRatio]
defaultValue = "0.001"

[setting.perpsBalMaxMarketSize]
defaultValue = "<%=String(33_624) %>"

[setting.perpsBalMaxMarketValue]
defaultValue = "<%=String(50_000) %>"

[setting.perpsBalInitialMarginRatio]
defaultValue = "3.94"

[setting.perpsBalMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsBalMaintenanceMarginScalar]
defaultValue = "0.35"

[setting.perpsBalFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsBalMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsBalMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsBalMinimumPositionMargin]
defaultValue = "50"

[setting.perpsBalLockedOiRatio]
defaultValue = "0.5"

[setting.perpsBalSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsBalMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsBalEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
