[setting.pythBchFeedId]
defaultValue = "0x3dd2b63686a450ec7290df3a1e0b583c0481f651351edfa7636f39aed55cf8a3"

[setting.perpsBchMarketId]
defaultValue = "4000"

[setting.perpsBchSkewScale]
defaultValue = "<%=String(84_375) %>"

[setting.perpsBchMaxFundingVelocity]
defaultValue = "36"

[setting.perpsBchMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsBchTakerFeeRatio]
defaultValue = "0.001"

[setting.perpsBchMaxMarketSize]
defaultValue = "<%=String(256) %>"

[setting.perpsBchMaxMarketValue]
defaultValue = "<%=String(50_000) %>"

[setting.perpsBchInitialMarginRatio]
defaultValue = "1.6"

[setting.perpsBchMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsBchMaintenanceMarginScalar]
defaultValue = "0.32"

[setting.perpsBchFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsBchMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsBchMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsBchMinimumPositionMargin]
defaultValue = "50"

[setting.perpsBchLockedOiRatio]
defaultValue = "0.5"

[setting.perpsBchSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsBchMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsBchEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
