[setting.perpsBlurMarketId]

[setting.perpsBlurSkewScale]

[setting.perpsBlurMaxFundingVelocity]

[setting.perpsBlurMakerFeeRatio]

[setting.perpsBlurTakerFeeRatio]

[setting.perpsBlurMaxMarketSize]

[setting.perpsBlurInitialMarginRatio]

[setting.perpsBlurMaintenanceMarginFraction]

[setting.perpsBlurFlagRewardRatioD18]

[setting.perpsBlurMaxLiquidationLimitAccumulationMultiplier]

[setting.perpsBlurMaxSecondsInLiquidationWindow]

[setting.perpsBlurMaxLiquidationPd]

[setting.perpsBlurEndorsedLiquidator]

[setting.perpsBlurMinimumPositionMargin]

[setting.perpsBlurLockedOiRatio]

[invoke.createBlurPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.perpsBlurMarketId %>", "Blur", "BLUR"]

[invoke.setPerpsPriceBlur]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.perpsBlurMarketId %>",
    "<%= extras.blur_oracle_id %>",
    "<%= settings.bigCapStrictStalenessTolerance %>",
]
depends = ["invoke.createBlurPerpsMarket"]

# Do not modify this step. Edit [invoke.setPerpsBlurSettlementStrategy] instead.
[invoke.addPerpsBlurSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [
    "<%= settings.perpsBlurMarketId %>",
    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.blur_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.blur_pyth_settlement_strategy.arg = 2
depends = ["invoke.createBlurPerpsMarket"]

[invoke.setPerpsBlurSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.perpsBlurMarketId %>",
    "<%= extras.blur_pyth_settlement_strategy %>",  # Settlement Strategy ID
    { strategyType = "0", settlementDelay = "<%= settings.bigCapSettlementDelay %>", settlementWindowDuration = "<%= settings.bigCapSettlementWindowDuration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pythBlurFeedId %>", settlementReward = "<%= parseEther(settings.settlementReward) %>", disabled = false, commitmentPriceDelay = "<%= settings.commitmentPriceDelay %>" },
]
depends = [
    'provision.perpsFactory',
    'setting.perpsBlurMarketId',
    'invoke.addPerpsBlurSettlementStrategy',
    'provision.pyth_erc7412_wrapper',
    'setting.bigCapSettlementDelay',
    'setting.bigCapSettlementWindowDuration',
    'setting.pythBlurFeedId',
    'setting.settlementReward',
    'setting.commitmentPriceDelay',
]
[invoke.setPerpsBlurFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.perpsBlurMarketId %>",
    "<%= parseEther(settings.perpsBlurSkewScale) %>",
    "<%= parseEther(settings.perpsBlurMaxFundingVelocity) %>",
]
depends = ["invoke.createBlurPerpsMarket"]

[invoke.setPerpsBlurOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.perpsBlurMarketId %>",
    "<%= parseEther(settings.perpsBlurMakerFeeRatio) %>",
    "<%= parseEther(settings.perpsBlurTakerFeeRatio) %>",
]
depends = ["invoke.createBlurPerpsMarket"]

[invoke.setPerpsBlurMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.perpsBlurMarketId %>", "<%= parseEther(settings.perpsBlurMaxMarketSize) %>"]
depends = ["invoke.createBlurPerpsMarket"]

[invoke.setPerpsBlurMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.perpsBlurMarketId %>", "<%= parseEther(settings.perpsBlurMaxMarketValue) %>"]
depends = ["invoke.createBlurPerpsMarket"]

[invoke.setPerpsBlurMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.perpsBlurMarketId %>",
    "<%= parseEther(settings.perpsBlurMaxLiquidationLimitAccumulationMultiplier) %>",
    "<%= settings.perpsBlurMaxSecondsInLiquidationWindow %>",
    "<%= parseEther(settings.perpsBlurMaxLiquidationPd) %>",
    "<%= settings.perpsBlurEndorsedLiquidator %>",
]
depends = ["invoke.createBlurPerpsMarket"]

[invoke.setPerpsBlurLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.perpsBlurMarketId %>",
    "<%= parseEther(settings.perpsBlurInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsBlurMinimumInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsBlurMaintenanceMarginScalar) %>",
    "<%= parseEther(settings.perpsBlurFlagRewardRatioD18) %>",
    "<%= parseEther(settings.perpsBlurMinimumPositionMargin) %>",
]
depends = ["invoke.createBlurPerpsMarket"]

[invoke.setPerpsBlurLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.perpsBlurMarketId %>", "<%= parseEther(settings.perpsBlurLockedOiRatio) %>"]
depends = ["invoke.createBlurPerpsMarket"]