[setting.pythBlurFeedId]
defaultValue = "0x856aac602516addee497edf6f50d39e8c95ae5fb0da1ed434a8c2ab9c3e877e9"

[setting.perpsBlurMarketId]
defaultValue = "4100"

[setting.perpsBlurSkewScale]
defaultValue = "<%=String(50_000_000) %>"

[setting.perpsBlurMaxFundingVelocity]
defaultValue = "36"

[setting.perpsBlurMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsBlurTakerFeeRatio]
defaultValue = "0.001"

[setting.perpsBlurMaxMarketSize]
defaultValue = "<%=String(496_684) %>"

[setting.perpsBlurMaxMarketValue]
defaultValue = "<%=String(50_000) %>"

[setting.perpsBlurInitialMarginRatio]
defaultValue = "1.49"

[setting.perpsBlurMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsBlurMaintenanceMarginScalar]
defaultValue = "0.37"

[setting.perpsBlurFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsBlurMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsBlurMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsBlurMinimumPositionMargin]
defaultValue = "50"

[setting.perpsBlurLockedOiRatio]
defaultValue = "0.5"

[setting.perpsBlurSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsBlurMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsBlurEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
