[setting.perpsCrvMarketId]

[setting.perpsCrvSkewScale]

[setting.perpsCrvMaxFundingVelocity]

[setting.perpsCrvMakerFeeRatio]

[setting.perpsCrvTakerFeeRatio]

[setting.perpsCrvMaxMarketSize]

[setting.perpsCrvInitialMarginRatio]

[setting.perpsCrvMaintenanceMarginFraction]

[setting.perpsCrvFlagRewardRatioD18]

[setting.perpsCrvMaxLiquidationLimitAccumulationMultiplier]

[setting.perpsCrvMaxSecondsInLiquidationWindow]

[setting.perpsCrvMaxLiquidationPd]

[setting.perpsCrvEndorsedLiquidator]

[setting.perpsCrvMinimumPositionMargin]

[setting.perpsCrvLockedOiRatio]

[invoke.createCrvPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.perpsCrvMarketId %>", "Curve Dao", "CRV"]

[invoke.setPerpsPriceCrv]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.perpsCrvMarketId %>",
    "<%= extras.crv_oracle_id %>",
    "<%= settings.bigCapStrictStalenessTolerance %>",
]
depends = ["invoke.createCrvPerpsMarket"]

# Do not modify this step. Edit [invoke.setPerpsCrvSettlementStrategy] instead.
[invoke.addPerpsCrvSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [
    "<%= settings.perpsCrvMarketId %>",
    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.crv_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.crv_pyth_settlement_strategy.arg = 2
depends = ["invoke.createCrvPerpsMarket"]

[invoke.setPerpsCrvSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.perpsCrvMarketId %>",
    "<%= extras.crv_pyth_settlement_strategy %>",  # Settlement Strategy ID
    { strategyType = "0", settlementDelay = "<%= settings.bigCapSettlementDelay %>", settlementWindowDuration = "<%= settings.bigCapSettlementWindowDuration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pythCrvFeedId %>", settlementReward = "<%= parseEther(settings.settlementReward) %>", disabled = false, commitmentPriceDelay = "<%= settings.commitmentPriceDelay %>" },
]
depends = [
    'provision.perpsFactory',
    'setting.perpsCrvMarketId',
    'invoke.addPerpsCrvSettlementStrategy',
    'provision.pyth_erc7412_wrapper',
    'setting.bigCapSettlementDelay',
    'setting.bigCapSettlementWindowDuration',
    'setting.pythCrvFeedId',
    'setting.settlementReward',
    'setting.commitmentPriceDelay',
]
[invoke.setPerpsCrvFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.perpsCrvMarketId %>",
    "<%= parseEther(settings.perpsCrvSkewScale) %>",
    "<%= parseEther(settings.perpsCrvMaxFundingVelocity) %>",
]
depends = ["invoke.createCrvPerpsMarket"]

[invoke.setPerpsCrvOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.perpsCrvMarketId %>",
    "<%= parseEther(settings.perpsCrvMakerFeeRatio) %>",
    "<%= parseEther(settings.perpsCrvTakerFeeRatio) %>",
]
depends = ["invoke.createCrvPerpsMarket"]

[invoke.setPerpsCrvMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.perpsCrvMarketId %>", "<%= parseEther(settings.perpsCrvMaxMarketSize) %>"]
depends = ["invoke.createCrvPerpsMarket"]

[invoke.setPerpsCrvMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.perpsCrvMarketId %>", "<%= parseEther(settings.perpsCrvMaxMarketValue) %>"]
depends = ["invoke.createCrvPerpsMarket"]

[invoke.setPerpsCrvMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.perpsCrvMarketId %>",
    "<%= parseEther(settings.perpsCrvMaxLiquidationLimitAccumulationMultiplier) %>",
    "<%= settings.perpsCrvMaxSecondsInLiquidationWindow %>",
    "<%= parseEther(settings.perpsCrvMaxLiquidationPd) %>",
    "<%= settings.perpsCrvEndorsedLiquidator %>",
]
depends = ["invoke.createCrvPerpsMarket"]

[invoke.setPerpsCrvLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.perpsCrvMarketId %>",
    "<%= parseEther(settings.perpsCrvInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsCrvMinimumInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsCrvMaintenanceMarginScalar) %>",
    "<%= parseEther(settings.perpsCrvFlagRewardRatioD18) %>",
    "<%= parseEther(settings.perpsCrvMinimumPositionMargin) %>",
]
depends = ["invoke.createCrvPerpsMarket"]

[invoke.setPerpsCrvLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.perpsCrvMarketId %>", "<%= parseEther(settings.perpsCrvLockedOiRatio) %>"]
depends = ["invoke.createCrvPerpsMarket"]