[setting.pythCrvFeedId]
defaultValue = "0xa19d04ac696c7a6616d291c7e5d1377cc8be437c327b75adb5dc1bad745fcae8"

[setting.perpsCrvMarketId]
defaultValue = "4300"

[setting.perpsCrvSkewScale]
defaultValue = "<%=String(60_000_000) %>"

[setting.perpsCrvMaxFundingVelocity]
defaultValue = "36"

[setting.perpsCrvMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsCrvTakerFeeRatio]
defaultValue = "0.001"

[setting.perpsCrvMaxMarketSize]
defaultValue = "<%=String(1_759_165) %>"

[setting.perpsCrvMaxMarketValue]
defaultValue = "<%=String(250_000) %>"

[setting.perpsCrvInitialMarginRatio]
defaultValue = "4.56"

[setting.perpsCrvMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsCrvMaintenanceMarginScalar]
defaultValue = "0.39"

[setting.perpsCrvFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsCrvMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsCrvMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsCrvMinimumPositionMargin]
defaultValue = "50"

[setting.perpsCrvLockedOiRatio]
defaultValue = "0.5"

[setting.perpsCrvSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsCrvMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsCrvEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
