[setting.perpsDotMarketId]

[setting.perpsDotSkewScale]

[setting.perpsDotMaxFundingVelocity]

[setting.perpsDotMakerFeeRatio]

[setting.perpsDotTakerFeeRatio]

[setting.perpsDotMaxMarketSize]

[setting.perpsDotInitialMarginRatio]

[setting.perpsDotMaintenanceMarginFraction]

[setting.perpsDotFlagRewardRatioD18]

[setting.perpsDotMaxLiquidationLimitAccumulationMultiplier]

[setting.perpsDotMaxSecondsInLiquidationWindow]

[setting.perpsDotMaxLiquidationPd]

[setting.perpsDotEndorsedLiquidator]

[setting.perpsDotMinimumPositionMargin]

[setting.perpsDotLockedOiRatio]

[invoke.createDotPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.perpsDotMarketId %>", "Polkadot", "DOT"]

[invoke.setPerpsPriceDot]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.perpsDotMarketId %>",
    "<%= extras.dot_oracle_id %>",
    "<%= settings.bigCapStrictStalenessTolerance %>",
]
depends = ["invoke.createDotPerpsMarket"]

# Do not modify this step. Edit [invoke.setPerpsDotSettlementStrategy] instead.
[invoke.addPerpsDotSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [
    "<%= settings.perpsDotMarketId %>",
    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.dot_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.dot_pyth_settlement_strategy.arg = 2
depends = ["invoke.createDotPerpsMarket"]

[invoke.setPerpsDotSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.perpsDotMarketId %>",
    "<%= extras.dot_pyth_settlement_strategy %>",  # Settlement Strategy ID
    { strategyType = "0", settlementDelay = "<%= settings.bigCapSettlementDelay %>", settlementWindowDuration = "<%= settings.bigCapSettlementWindowDuration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pythDotFeedId %>", settlementReward = "<%= parseEther(settings.settlementReward) %>", disabled = false, commitmentPriceDelay = "<%= settings.commitmentPriceDelay %>" },
]
depends = [
    'provision.perpsFactory',
    'setting.perpsDotMarketId',
    'invoke.addPerpsDotSettlementStrategy',
    'provision.pyth_erc7412_wrapper',
    'setting.bigCapSettlementDelay',
    'setting.bigCapSettlementWindowDuration',
    'setting.pythDotFeedId',
    'setting.settlementReward',
    'setting.commitmentPriceDelay',
]
[invoke.setPerpsDotFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.perpsDotMarketId %>",
    "<%= parseEther(settings.perpsDotSkewScale) %>",
    "<%= parseEther(settings.perpsDotMaxFundingVelocity) %>",
]
depends = ["invoke.createDotPerpsMarket"]

[invoke.setPerpsDotOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.perpsDotMarketId %>",
    "<%= parseEther(settings.perpsDotMakerFeeRatio) %>",
    "<%= parseEther(settings.perpsDotTakerFeeRatio) %>",
]
depends = ["invoke.createDotPerpsMarket"]

[invoke.setPerpsDotMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.perpsDotMarketId %>", "<%= parseEther(settings.perpsDotMaxMarketSize) %>"]
depends = ["invoke.createDotPerpsMarket"]

[invoke.setPerpsDotMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.perpsDotMarketId %>", "<%= parseEther(settings.perpsDotMaxMarketValue) %>"]
depends = ["invoke.createDotPerpsMarket"]

[invoke.setPerpsDotMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.perpsDotMarketId %>",
    "<%= parseEther(settings.perpsDotMaxLiquidationLimitAccumulationMultiplier) %>",
    "<%= settings.perpsDotMaxSecondsInLiquidationWindow %>",
    "<%= parseEther(settings.perpsDotMaxLiquidationPd) %>",
    "<%= settings.perpsDotEndorsedLiquidator %>",
]
depends = ["invoke.createDotPerpsMarket"]

[invoke.setPerpsDotLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.perpsDotMarketId %>",
    "<%= parseEther(settings.perpsDotInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsDotMinimumInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsDotMaintenanceMarginScalar) %>",
    "<%= parseEther(settings.perpsDotFlagRewardRatioD18) %>",
    "<%= parseEther(settings.perpsDotMinimumPositionMargin) %>",
]
depends = ["invoke.createDotPerpsMarket"]

[invoke.setPerpsDotLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.perpsDotMarketId %>", "<%= parseEther(settings.perpsDotLockedOiRatio) %>"]
depends = ["invoke.createDotPerpsMarket"]