[setting.pythEthbtcFeedId]
defaultValue = "0xc96458d393fe9deb7a7d63a0ac41e2898a67a7750dbd166673279e06c868df0a"

[setting.perpsEthbtcMarketId]
defaultValue = "4800"

[setting.perpsEthbtcSkewScale]
defaultValue = "<%=String(850_000_000) %>"

[setting.perpsEthbtcMaxFundingVelocity]
defaultValue = "9"

[setting.perpsEthbtcMakerFeeRatio]
defaultValue = "1e-07"

[setting.perpsEthbtcTakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsEthbtcMaxMarketSize]
defaultValue = "<%=String(72_226_506) %>"

[setting.perpsEthbtcMaxMarketValue]
defaultValue = "<%=String(2_000_000) %>"

[setting.perpsEthbtcInitialMarginRatio]
defaultValue = "1.39"

[setting.perpsEthbtcMinimumInitialMarginRatio]
defaultValue = "0.02"

[setting.perpsEthbtcMaintenanceMarginScalar]
defaultValue = "0.26"

[setting.perpsEthbtcFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsEthbtcMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsEthbtcMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsEthbtcMinimumPositionMargin]
defaultValue = "50"

[setting.perpsEthbtcLockedOiRatio]
defaultValue = "0.5"

[setting.perpsEthbtcSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsEthbtcMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsEthbtcEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
