[setting.perpsFilMarketId]

[setting.perpsFilSkewScale]

[setting.perpsFilMaxFundingVelocity]

[setting.perpsFilMakerFeeRatio]

[setting.perpsFilTakerFeeRatio]

[setting.perpsFilMaxMarketSize]

[setting.perpsFilInitialMarginRatio]

[setting.perpsFilMaintenanceMarginFraction]

[setting.perpsFilFlagRewardRatioD18]

[setting.perpsFilMaxLiquidationLimitAccumulationMultiplier]

[setting.perpsFilMaxSecondsInLiquidationWindow]

[setting.perpsFilMaxLiquidationPd]

[setting.perpsFilEndorsedLiquidator]

[setting.perpsFilMinimumPositionMargin]

[setting.perpsFilLockedOiRatio]

[invoke.createFilPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.perpsFilMarketId %>", "Filecoin", "FIL"]

[invoke.setPerpsPriceFil]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.perpsFilMarketId %>",
    "<%= extras.fil_oracle_id %>",
    "<%= settings.bigCapStrictStalenessTolerance %>",
]
depends = ["invoke.createFilPerpsMarket"]

# Do not modify this step. Edit [invoke.setPerpsFilSettlementStrategy] instead.
[invoke.addPerpsFilSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [
    "<%= settings.perpsFilMarketId %>",
    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.fil_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.fil_pyth_settlement_strategy.arg = 2
depends = ["invoke.createFilPerpsMarket"]

[invoke.setPerpsFilSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.perpsFilMarketId %>",
    "<%= extras.fil_pyth_settlement_strategy %>",  # Settlement Strategy ID
    { strategyType = "0", settlementDelay = "<%= settings.bigCapSettlementDelay %>", settlementWindowDuration = "<%= settings.bigCapSettlementWindowDuration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pythFilFeedId %>", settlementReward = "<%= parseEther(settings.settlementReward) %>", disabled = false, commitmentPriceDelay = "<%= settings.commitmentPriceDelay %>" },
]
depends = [
    'provision.perpsFactory',
    'setting.perpsFilMarketId',
    'invoke.addPerpsFilSettlementStrategy',
    'provision.pyth_erc7412_wrapper',
    'setting.bigCapSettlementDelay',
    'setting.bigCapSettlementWindowDuration',
    'setting.pythFilFeedId',
    'setting.settlementReward',
    'setting.commitmentPriceDelay',
]
[invoke.setPerpsFilFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.perpsFilMarketId %>",
    "<%= parseEther(settings.perpsFilSkewScale) %>",
    "<%= parseEther(settings.perpsFilMaxFundingVelocity) %>",
]
depends = ["invoke.createFilPerpsMarket"]

[invoke.setPerpsFilOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.perpsFilMarketId %>",
    "<%= parseEther(settings.perpsFilMakerFeeRatio) %>",
    "<%= parseEther(settings.perpsFilTakerFeeRatio) %>",
]
depends = ["invoke.createFilPerpsMarket"]

[invoke.setPerpsFilMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.perpsFilMarketId %>", "<%= parseEther(settings.perpsFilMaxMarketSize) %>"]
depends = ["invoke.createFilPerpsMarket"]

[invoke.setPerpsFilMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.perpsFilMarketId %>", "<%= parseEther(settings.perpsFilMaxMarketValue) %>"]
depends = ["invoke.createFilPerpsMarket"]

[invoke.setPerpsFilMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.perpsFilMarketId %>",
    "<%= parseEther(settings.perpsFilMaxLiquidationLimitAccumulationMultiplier) %>",
    "<%= settings.perpsFilMaxSecondsInLiquidationWindow %>",
    "<%= parseEther(settings.perpsFilMaxLiquidationPd) %>",
    "<%= settings.perpsFilEndorsedLiquidator %>",
]
depends = ["invoke.createFilPerpsMarket"]

[invoke.setPerpsFilLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.perpsFilMarketId %>",
    "<%= parseEther(settings.perpsFilInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsFilMinimumInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsFilMaintenanceMarginScalar) %>",
    "<%= parseEther(settings.perpsFilFlagRewardRatioD18) %>",
    "<%= parseEther(settings.perpsFilMinimumPositionMargin) %>",
]
depends = ["invoke.createFilPerpsMarket"]

[invoke.setPerpsFilLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.perpsFilMarketId %>", "<%= parseEther(settings.perpsFilLockedOiRatio) %>"]
depends = ["invoke.createFilPerpsMarket"]