[setting.pythFxsFeedId]
defaultValue = "0x735f591e4fed988cd38df74d8fcedecf2fe8d9111664e0fd500db9aa78b316b1"

[setting.perpsFxsMarketId]
defaultValue = "5100"

[setting.perpsFxsSkewScale]
defaultValue = "<%=String(703_125) %>"

[setting.perpsFxsMaxFundingVelocity]
defaultValue = "36"

[setting.perpsFxsMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsFxsTakerFeeRatio]
defaultValue = "0.001"

[setting.perpsFxsMaxMarketSize]
defaultValue = "<%=String(33_029) %>"

[setting.perpsFxsMaxMarketValue]
defaultValue = "<%=String(50_000) %>"

[setting.perpsFxsInitialMarginRatio]
defaultValue = "2.59"

[setting.perpsFxsMinimumInitialMarginRatio]
defaultValue = "0.06666"

[setting.perpsFxsMaintenanceMarginScalar]
defaultValue = "0.34"

[setting.perpsFxsFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsFxsMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsFxsMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsFxsMinimumPositionMargin]
defaultValue = "50"

[setting.perpsFxsLockedOiRatio]
defaultValue = "0.5"

[setting.perpsFxsSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsFxsMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsFxsEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
