[setting.pythLtcFeedId]
defaultValue = "0x6e3f3fa8253588df9326580180233eb791e03b443a3ba7a1d892e73874e19a54"

[setting.perpsLtcMarketId]
defaultValue = "5800"

[setting.perpsLtcSkewScale]
defaultValue = "<%=String(1_687_500) %>"

[setting.perpsLtcMaxFundingVelocity]
defaultValue = "36"

[setting.perpsLtcMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsLtcTakerFeeRatio]
defaultValue = "0.001"

[setting.perpsLtcMaxMarketSize]
defaultValue = "<%=String(1_330) %>"

[setting.perpsLtcMaxMarketValue]
defaultValue = "<%=String(50_000) %>"

[setting.perpsLtcInitialMarginRatio]
defaultValue = "0.005"

[setting.perpsLtcMinimumInitialMarginRatio]
defaultValue = "0.02"

[setting.perpsLtcMaintenanceMarginScalar]
defaultValue = "0.4"

[setting.perpsLtcFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsLtcMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsLtcMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsLtcMinimumPositionMargin]
defaultValue = "50"

[setting.perpsLtcLockedOiRatio]
defaultValue = "0.5"

[setting.perpsLtcSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsLtcMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsLtcEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
