include = [
    # TODO: this is a funny necessary dependency because the oracle manager is registering the same node twice
    # however, it will not emit "NodeRegistered" the second time because its an unnecessary call
    "../../oracles/pyth-rune.toml",
    "../../markets/common/bigcap-settings.toml",
]
# NOTE: This toml will live until the setMaxMarketValue is on mainnet

[setting.perpsRuneMarketId]

[setting.perpsRuneSkewScale]

[setting.perpsRuneMaxFundingVelocity]

[setting.perpsRuneMakerFeeRatio]

[setting.perpsRuneTakerFeeRatio]

[setting.perpsRuneMaxMarketSize]

[setting.perpsRuneInitialMarginRatio]

[setting.perpsRuneMaintenanceMarginFraction]

[setting.perpsRuneFlagRewardRatioD18]

[setting.perpsRuneMaxLiquidationLimitAccumulationMultiplier]

[setting.perpsRuneMaxSecondsInLiquidationWindow]

[setting.perpsRuneMaxLiquidationPd]

[setting.perpsRuneEndorsedLiquidator]

[setting.perpsRuneMinimumPositionMargin]

[setting.perpsRuneLockedOiRatio]

[invoke.createRunePerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.perpsRuneMarketId %>", "THORChain", "RUNE"]

[invoke.setPerpsPriceRune]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.perpsRuneMarketId %>",
    "<%= extras.rune_oracle_id %>",
    "<%= settings.bigCapStrictStalenessTolerance %>",
]
depends = ["invoke.createRunePerpsMarket"]

# Do not modify this step. Edit [invoke.setPerpsRuneSettlementStrategy] instead.
[invoke.addPerpsRuneSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [
    "<%= settings.perpsRuneMarketId %>",
    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.rune_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.rune_pyth_settlement_strategy.arg = 2
depends = ["invoke.createRunePerpsMarket"]

[invoke.setPerpsRuneSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.perpsRuneMarketId %>",
    "<%= extras.rune_pyth_settlement_strategy %>",                                                                                                                                                                                                                                                                                                                                                                                                                         # Settlement Strategy ID
    { strategyType = "0", settlementDelay = "<%= settings.bigCapSettlementDelay %>", settlementWindowDuration = "<%= settings.bigCapSettlementWindowDuration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pythRuneFeedId %>", settlementReward = "<%= parseEther(settings.settlementReward) %>", disabled = false, commitmentPriceDelay = "<%= settings.commitmentPriceDelay %>" },
]
depends = [
    'provision.perpsFactory',
    'setting.perpsRuneMarketId',
    'invoke.addPerpsRuneSettlementStrategy',
    'provision.pyth_erc7412_wrapper',
    'setting.bigCapSettlementDelay',
    'setting.bigCapSettlementWindowDuration',
    'setting.pythRuneFeedId',
    'setting.settlementReward',
    'setting.commitmentPriceDelay',
]
[invoke.setPerpsRuneFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.perpsRuneMarketId %>",
    "<%= parseEther(settings.perpsRuneSkewScale) %>",
    "<%= parseEther(settings.perpsRuneMaxFundingVelocity) %>",
]
depends = ["invoke.createRunePerpsMarket"]

[invoke.setPerpsRuneOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.perpsRuneMarketId %>",
    "<%= parseEther(settings.perpsRuneMakerFeeRatio) %>",
    "<%= parseEther(settings.perpsRuneTakerFeeRatio) %>",
]
depends = ["invoke.createRunePerpsMarket"]

[invoke.setPerpsRuneMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.perpsRuneMarketId %>", "<%= parseEther(settings.perpsRuneMaxMarketSize) %>"]
depends = ["invoke.createRunePerpsMarket"]

[invoke.setPerpsRuneMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.perpsRuneMarketId %>", "<%= parseEther(settings.perpsRuneMaxMarketValue) %>"]
depends = ["invoke.createRunePerpsMarket"]

[invoke.setPerpsRuneMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.perpsRuneMarketId %>",
    "<%= parseEther(settings.perpsRuneMaxLiquidationLimitAccumulationMultiplier) %>",
    "<%= settings.perpsRuneMaxSecondsInLiquidationWindow %>",
    "<%= parseEther(settings.perpsRuneMaxLiquidationPd) %>",
    "<%= settings.perpsRuneEndorsedLiquidator %>",
]
depends = ["invoke.createRunePerpsMarket"]

[invoke.setPerpsRuneLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.perpsRuneMarketId %>",
    "<%= parseEther(settings.perpsRuneInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsRuneMinimumInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsRuneMaintenanceMarginScalar) %>",
    "<%= parseEther(settings.perpsRuneFlagRewardRatioD18) %>",
    "<%= parseEther(settings.perpsRuneMinimumPositionMargin) %>",
]
depends = ["invoke.createRunePerpsMarket"]

[invoke.setPerpsRuneLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.perpsRuneMarketId %>", "<%= parseEther(settings.perpsRuneLockedOiRatio) %>"]
depends = ["invoke.createRunePerpsMarket"]
