[setting.pythSeiFeedId]
defaultValue = "0x53614f1cb0c031d4af66c04cb9c756234adad0e1cee85303795091499a4084eb"

[setting.perpsSeiMarketId]
defaultValue = "6400"

[setting.perpsSeiSkewScale]
defaultValue = "<%=String(35_500_000) %>"

[setting.perpsSeiMaxFundingVelocity]
defaultValue = "36"

[setting.perpsSeiMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsSeiTakerFeeRatio]
defaultValue = "0.001"

[setting.perpsSeiMaxMarketSize]
defaultValue = "<%=String(293_317) %>"

[setting.perpsSeiMaxMarketValue]
defaultValue = "<%=String(50_000) %>"

[setting.perpsSeiInitialMarginRatio]
defaultValue = "5.13"

[setting.perpsSeiMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsSeiMaintenanceMarginScalar]
defaultValue = "0.39"

[setting.perpsSeiFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsSeiMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsSeiMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsSeiMinimumPositionMargin]
defaultValue = "50"

[setting.perpsSeiLockedOiRatio]
defaultValue = "0.5"

[setting.perpsSeiSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsSeiMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsSeiEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
