[setting.pythStxFeedId]
defaultValue = "0xec7a775f46379b5e943c3526b1c8d54cd49749176b0b98e02dde68d1bd335c17"

[setting.perpsStxMarketId]
defaultValue = "3100"

[setting.perpsStxSkewScale]
defaultValue = "<%= String(7_500_000) %>"

[setting.perpsStxMaxFundingVelocity]
defaultValue = "36"

[setting.perpsStxMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsStxTakerFeeRatio]
defaultValue = "0.0010"

[setting.perpsStxMaxMarketSize]
defaultValue = "<%= String(200_000) %>"

[setting.perpsStxMaxMarketValue]
defaultValue = "<%= String(500_000) %>"

[setting.perpsStxInitialMarginRatio]
defaultValue = "2.61"

[setting.perpsStxMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsStxMaintenanceMarginScalar]
defaultValue = "0.43"

[setting.perpsStxFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsStxMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsStxMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsStxMinimumPositionMargin]
defaultValue = "50"

[setting.perpsStxLockedOiRatio]
defaultValue = "0.5"

[setting.perpsStxSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsStxMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsStxEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
