[setting.pythSushiFeedId]
defaultValue = "0x26e4f737fde0263a9eea10ae63ac36dcedab2aaf629261a994e1eeb6ee0afe53"

[setting.perpsSushiMarketId]
defaultValue = "6700"

[setting.perpsSushiSkewScale]
defaultValue = "<%=String(7_875_000) %>"

[setting.perpsSushiMaxFundingVelocity]
defaultValue = "36"

[setting.perpsSushiMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsSushiTakerFeeRatio]
defaultValue = "0.001"

[setting.perpsSushiMaxMarketSize]
defaultValue = "<%=String(117_960) %>"

[setting.perpsSushiMaxMarketValue]
defaultValue = "<%=String(50_000) %>"

[setting.perpsSushiInitialMarginRatio]
defaultValue = "1.37"

[setting.perpsSushiMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsSushiMaintenanceMarginScalar]
defaultValue = "0.4"

[setting.perpsSushiFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsSushiMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsSushiMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsSushiMinimumPositionMargin]
defaultValue = "50"

[setting.perpsSushiLockedOiRatio]
defaultValue = "0.5"

[setting.perpsSushiSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsSushiMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsSushiEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
