[setting.pythTaoFeedId]
defaultValue = "0x410f41de235f2db824e562ea7ab2d3d3d4ff048316c61d629c0b93f58584e1af"

[setting.perpsTaoMarketId]
defaultValue = "2800"

[setting.perpsTaoSkewScale]
defaultValue = "<%= String(16_250) %>"

[setting.perpsTaoMaxFundingVelocity]
defaultValue = "36"

[setting.perpsTaoMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsTaoTakerFeeRatio]
defaultValue = "0.0010"

[setting.perpsTaoMaxMarketSize]
defaultValue = "<%= String(2_000) %>"

[setting.perpsTaoMaxMarketValue]
defaultValue = "<%= String(500_000) %>"

[setting.perpsTaoInitialMarginRatio]
defaultValue = "2.89"

[setting.perpsTaoMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsTaoMaintenanceMarginScalar]
defaultValue = "0.37"

[setting.perpsTaoFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsTaoMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsTaoMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsTaoMinimumPositionMargin]
defaultValue = "50"

[setting.perpsTaoLockedOiRatio]
defaultValue = "0.5"

[setting.perpsTaoSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsTaoMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsTaoEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
