[setting.snx_package]
defaultValue = "synthetix:3.0.0"

[setting.owner]

[setting.salt]
defaultValue = "alpha"

[provision.system]
source = "<%= settings.snx_package %>"
options.owner = "<%= settings.owner %>"
options.salt = "<%= settings.salt %>"
