[setting.minimum_liquidity_ratio]

[setting.account_timeout_withdraw]

[setting.ccip_router]

[setting.ccip_token_pool]

[invoke.setMinimumLiquidityRatio]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setMinLiquidityRatio(uint256)"
args = ["<%= settings.minimum_liquidity_ratio %>"]
depends = ["provision.system"]

[invoke.setAccountTimeoutWithdraw]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setConfig"
args = [
    "<%= formatBytes32String('accountTimeoutWithdraw') %>",
    "<%= hexZeroPad(hexlify(parseInt(settings.account_timeout_withdraw)), 32) %>"
]
depends = ["provision.system"]

[invoke.configureChainlinkCrossChain]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureChainlinkCrossChain"
args = ["<%= settings.ccip_router %>"]

[invoke.configureUsdTokenChainlink]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureUsdTokenChainlink"
args = ["<%= settings.ccip_router %>", "<%= settings.ccip_token_pool %>"]
