include = [
    "settings.toml",
]

[invoke.setSupportedCrossChainNetworks]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setSupportedCrossChainNetworks"
args = [
  ["11155111", "420", "421613", "80001"], 
  ["16015286601757825753", "2664363617261496610", "6101244977088475029", "12532609583862916517"]
]
depends = ["provision.system"]