[var.perps_atom_market_settings]
atom_perps_market_id = "3400"
atom_perps_market_skew_scale = "<%= parseEther(String(11_250_000)) %>"
atom_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
atom_perps_maker_fee_ratio = "<%= parseEther('0.000000') %>"
atom_perps_taker_fee_ratio = "<%= parseEther('0.000500') %>"
atom_perps_max_market_size = "<%= parseEther(String(329_300)) %>"
atom_perps_max_market_value = "<%= parseEther(String(1_000_000)) %>"
atom_perps_initial_margin_ratio = "<%= parseEther('2.49') %>"
atom_perps_maintenance_margin_scalar = "<%= parseEther('0.31') %>"
atom_perps_minimum_initial_margin_ratio = "<%= parseEther('0.05') %>"
atom_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
atom_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
atom_perps_max_seconds_in_liquidation_window = "30"
atom_perps_minimum_position_margin = "<%= parseEther('50') %>"
atom_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
atom_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
atom_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createAtomPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.atom_perps_market_id %>", "Cosmos", "ATOM"]

[invoke.setPerpsPriceAtom]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.atom_perps_market_id %>",
    "<%= extras.atom_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsAtomSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.atom_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.atom_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.atom_pyth_settlement_strategy.arg = 2
[invoke.setPerpsAtomSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.atom_perps_market_id %>",
    "<%= extras.atom_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_atom %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsAtomFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.atom_perps_market_id %>",
    "<%= settings.atom_perps_market_skew_scale %>",
    "<%= settings.atom_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsAtomOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.atom_perps_market_id %>",
    "<%= settings.atom_perps_maker_fee_ratio %>",
    "<%= settings.atom_perps_taker_fee_ratio %>",
]

[invoke.setPerpsAtomMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.atom_perps_market_id %>", "<%= settings.atom_perps_max_market_size %>"]

[invoke.setPerpsAtomMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.atom_perps_market_id %>", "<%= settings.atom_perps_max_market_value %>"]

[invoke.setPerpsAtomMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.atom_perps_market_id %>",
    "<%= settings.atom_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.atom_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.atom_perps_max_liquidation_pd %>",
    "<%= settings.atom_perps_endorsed_liquidator %>",
]

[invoke.setPerpsAtomLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.atom_perps_market_id %>",
    "<%= settings.atom_perps_initial_margin_ratio %>",
    "<%= settings.atom_perps_minimum_initial_margin_ratio %>",
    "<%= settings.atom_perps_maintenance_margin_scalar %>",
    "<%= settings.atom_perps_flag_reward_ratio_d18 %>",
    "<%= settings.atom_perps_minimum_position_margin %>",
]

[invoke.setPerpsAtomLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.atom_perps_market_id %>", "<%= settings.atom_perps_locked_oi_ratio %>"]
