[var.perps_eos_market_settings]
eos_perps_market_id = "4400"
eos_perps_market_skew_scale = "<%= parseEther(String(72_000_000)) %>"
eos_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
eos_perps_maker_fee_ratio = "<%= parseEther('0.000000') %>"
eos_perps_taker_fee_ratio = "<%= parseEther('0.000500') %>"
eos_perps_max_market_size = "<%= parseEther(String(3_182_150)) %>"
eos_perps_max_market_value = "<%= parseEther(String(1_000_000)) %>"
eos_perps_initial_margin_ratio = "<%= parseEther('2.47') %>"
eos_perps_maintenance_margin_scalar = "<%= parseEther('0.33') %>"
eos_perps_minimum_initial_margin_ratio = "<%= parseEther('0.05') %>"
eos_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
eos_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
eos_perps_max_seconds_in_liquidation_window = "30"
eos_perps_minimum_position_margin = "<%= parseEther('50') %>"
eos_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
eos_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
eos_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createEosPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.eos_perps_market_id %>", "Eos", "EOS"]

[invoke.setPerpsPriceEos]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.eos_perps_market_id %>",
    "<%= extras.eos_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsEosSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.eos_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.eos_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.eos_pyth_settlement_strategy.arg = 2
[invoke.setPerpsEosSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.eos_perps_market_id %>",
    "<%= extras.eos_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_eos %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsEosFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.eos_perps_market_id %>",
    "<%= settings.eos_perps_market_skew_scale %>",
    "<%= settings.eos_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsEosOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.eos_perps_market_id %>",
    "<%= settings.eos_perps_maker_fee_ratio %>",
    "<%= settings.eos_perps_taker_fee_ratio %>",
]

[invoke.setPerpsEosMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.eos_perps_market_id %>", "<%= settings.eos_perps_max_market_size %>"]

[invoke.setPerpsEosMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.eos_perps_market_id %>", "<%= settings.eos_perps_max_market_value %>"]

[invoke.setPerpsEosMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.eos_perps_market_id %>",
    "<%= settings.eos_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.eos_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.eos_perps_max_liquidation_pd %>",
    "<%= settings.eos_perps_endorsed_liquidator %>",
]

[invoke.setPerpsEosLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.eos_perps_market_id %>",
    "<%= settings.eos_perps_initial_margin_ratio %>",
    "<%= settings.eos_perps_minimum_initial_margin_ratio %>",
    "<%= settings.eos_perps_maintenance_margin_scalar %>",
    "<%= settings.eos_perps_flag_reward_ratio_d18 %>",
    "<%= settings.eos_perps_minimum_position_margin %>",
]

[invoke.setPerpsEosLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.eos_perps_market_id %>", "<%= settings.eos_perps_locked_oi_ratio %>"]
