[var.perps_render_market_settings]
render_perps_market_id = "7800"
render_perps_market_skew_scale = "<%= parseEther(String(2_250_000)) %>"
render_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
render_perps_maker_fee_ratio = "<%= parseEther('0.000000') %>"
render_perps_taker_fee_ratio = "<%= parseEther('0.000500') %>"
render_perps_max_market_size = "<%= parseEther(String(179_630)) %>"
render_perps_max_market_value = "<%= parseEther(String(1_000_000)) %>"
render_perps_initial_margin_ratio = "<%= parseEther('1.467') %>"
render_perps_maintenance_margin_scalar = "<%= parseEther('0.325') %>"
render_perps_minimum_initial_margin_ratio = "<%= parseEther('0.05') %>"
render_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
render_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
render_perps_max_seconds_in_liquidation_window = "30"
render_perps_minimum_position_margin = "<%= parseEther('50') %>"
render_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
render_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
render_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createRenderPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.render_perps_market_id %>", "Render", "RENDER"]

[invoke.setPerpsPriceRender]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.render_perps_market_id %>",
    "<%= extras.render_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsRenderSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.render_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.render_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.render_pyth_settlement_strategy.arg = 2
[invoke.setPerpsRenderSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.render_perps_market_id %>",
    "<%= extras.render_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_render %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsRenderFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.render_perps_market_id %>",
    "<%= settings.render_perps_market_skew_scale %>",
    "<%= settings.render_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsRenderOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.render_perps_market_id %>",
    "<%= settings.render_perps_maker_fee_ratio %>",
    "<%= settings.render_perps_taker_fee_ratio %>",
]

[invoke.setPerpsRenderMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.render_perps_market_id %>", "<%= settings.render_perps_max_market_size %>"]

[invoke.setPerpsRenderMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.render_perps_market_id %>", "<%= settings.render_perps_max_market_value %>"]

[invoke.setPerpsRenderMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.render_perps_market_id %>",
    "<%= settings.render_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.render_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.render_perps_max_liquidation_pd %>",
    "<%= settings.render_perps_endorsed_liquidator %>",
]

[invoke.setPerpsRenderLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.render_perps_market_id %>",
    "<%= settings.render_perps_initial_margin_ratio %>",
    "<%= settings.render_perps_minimum_initial_margin_ratio %>",
    "<%= settings.render_perps_maintenance_margin_scalar %>",
    "<%= settings.render_perps_flag_reward_ratio_d18 %>",
    "<%= settings.render_perps_minimum_position_margin %>",
]

[invoke.setPerpsRenderLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.render_perps_market_id %>", "<%= settings.render_perps_locked_oi_ratio %>"]
