[var.perps_tao_market_settings]
tao_perps_market_id = "6700"
tao_perps_market_skew_scale = "<%= parseEther(String(32_500)) %>"
tao_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
tao_perps_maker_fee_ratio = "<%= parseEther('0.000000') %>"
tao_perps_taker_fee_ratio = "<%= parseEther('0.000500') %>"
tao_perps_max_market_size = "<%= parseEther(String(2_450)) %>"
tao_perps_max_market_value = "<%= parseEther(String(1_000_000)) %>"
tao_perps_initial_margin_ratio = "<%= parseEther('2.89') %>"
tao_perps_maintenance_margin_scalar = "<%= parseEther('0.37') %>"
tao_perps_minimum_initial_margin_ratio = "<%= parseEther('0.05') %>"
tao_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
tao_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
tao_perps_max_seconds_in_liquidation_window = "30"
tao_perps_minimum_position_margin = "<%= parseEther('50') %>"
tao_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
tao_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
tao_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createTaoPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.tao_perps_market_id %>", "Bittensor", "TAO"]

[invoke.setPerpsPriceTao]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.tao_perps_market_id %>",
    "<%= extras.tao_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsTaoSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.tao_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.tao_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.tao_pyth_settlement_strategy.arg = 2
[invoke.setPerpsTaoSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.tao_perps_market_id %>",
    "<%= extras.tao_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_tao %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsTaoFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.tao_perps_market_id %>",
    "<%= settings.tao_perps_market_skew_scale %>",
    "<%= settings.tao_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsTaoOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.tao_perps_market_id %>",
    "<%= settings.tao_perps_maker_fee_ratio %>",
    "<%= settings.tao_perps_taker_fee_ratio %>",
]

[invoke.setPerpsTaoMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.tao_perps_market_id %>", "<%= settings.tao_perps_max_market_size %>"]

[invoke.setPerpsTaoMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.tao_perps_market_id %>", "<%= settings.tao_perps_max_market_value %>"]

[invoke.setPerpsTaoMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.tao_perps_market_id %>",
    "<%= settings.tao_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.tao_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.tao_perps_max_liquidation_pd %>",
    "<%= settings.tao_perps_endorsed_liquidator %>",
]

[invoke.setPerpsTaoLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.tao_perps_market_id %>",
    "<%= settings.tao_perps_initial_margin_ratio %>",
    "<%= settings.tao_perps_minimum_initial_margin_ratio %>",
    "<%= settings.tao_perps_maintenance_margin_scalar %>",
    "<%= settings.tao_perps_flag_reward_ratio_d18 %>",
    "<%= settings.tao_perps_minimum_position_margin %>",
]

[invoke.setPerpsTaoLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.tao_perps_market_id %>", "<%= settings.tao_perps_locked_oi_ratio %>"]
