[setting.deployer]

[setting.perps_pool_id]

[setting.pool_owner]

[invoke.createPerpsPool]
target = ["system.CoreProxy"]
from = "<%= settings.deployer %>"
func = "createPool"
args = ["<%= settings.perps_pool_id %>", "<%= settings.pool_owner %>"]
depends = ["invoke.permitCreatePool"]

[invoke.setPerpsPoolName]
target = ["system.CoreProxy"]
fromCall.func = "getPoolOwner"
fromCall.args = ["<%= settings.perps_pool_id %>"]
func = "setPoolName"
args = ["<%= settings.perps_pool_id %>", "Perps Pool"]
depends = ["invoke.createPerpsPool"]

[invoke.setPerpsPreferredPool]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setPreferredPool"
args = ["<%= settings.perps_pool_id %>"]
depends = ["invoke.createPerpsPool"]
