[setting.deployer]

[setting.spots_pool_id]

[setting.pool_owner]

[invoke.createSpotsPool]
target = ["system.CoreProxy"]
from = "<%= settings.deployer %>"
func = "createPool"
args = ["<%= settings.spots_pool_id %>", "<%= settings.pool_owner %>"]
depends = ["invoke.permitCreatePool"]

[invoke.setSpotsPoolName]
target = ["system.CoreProxy"]
fromCall.func = "getPoolOwner"
fromCall.args = ["<%= settings.spots_pool_id %>"]
func = "setPoolName"
args = ["<%= settings.spots_pool_id %>", "Spots Pool"]
depends = ["invoke.createSpotsPool"]

[invoke.setSpotsPreferredPool]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setPreferredPool"
args = ["<%= settings.spots_pool_id %>"]
depends = ["invoke.createSpotsPool"]
