[var.perps_arb_market_settings]
arb_perps_market_id = "1600"
arb_perps_market_skew_scale = "<%= parseEther(String(82_000_000)) %>"
arb_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
arb_perps_maker_fee_ratio = "<%= parseEther('0.000200') %>"
arb_perps_taker_fee_ratio = "<%= parseEther('0.001000') %>"
arb_perps_max_market_size = "<%= parseEther(String(2_000_000)) %>"
arb_perps_max_market_value = "<%= parseEther(String(1_000_000)) %>"
arb_perps_initial_margin_ratio = "<%= parseEther('4.16') %>"
arb_perps_maintenance_margin_scalar = "<%= parseEther('0.38') %>"
arb_perps_minimum_initial_margin_ratio = "<%= parseEther('0.033333') %>"
arb_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
arb_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
arb_perps_max_seconds_in_liquidation_window = "30"
arb_perps_minimum_position_margin = "<%= parseEther('50') %>"
arb_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
arb_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
arb_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createArbPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.arb_perps_market_id %>", "Arbitrum", "ARB"]

[invoke.setPerpsPriceArb]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.arb_perps_market_id %>",
    "<%= extras.arb_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsArbSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.arb_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.arb_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.arb_pyth_settlement_strategy.arg = 2
[invoke.setPerpsArbSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.arb_perps_market_id %>",
    "<%= extras.arb_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_arb %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsArbFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.arb_perps_market_id %>",
    "<%= settings.arb_perps_market_skew_scale %>",
    "<%= settings.arb_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsArbOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.arb_perps_market_id %>",
    "<%= settings.arb_perps_maker_fee_ratio %>",
    "<%= settings.arb_perps_taker_fee_ratio %>",
]

[invoke.setPerpsArbMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.arb_perps_market_id %>", "<%= settings.arb_perps_max_market_size %>"]

[invoke.setPerpsArbMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.arb_perps_market_id %>", "<%= settings.arb_perps_max_market_value %>"]

[invoke.setPerpsArbMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.arb_perps_market_id %>",
    "<%= settings.arb_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.arb_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.arb_perps_max_liquidation_pd %>",
    "<%= settings.arb_perps_endorsed_liquidator %>",
]

[invoke.setPerpsArbLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.arb_perps_market_id %>",
    "<%= settings.arb_perps_initial_margin_ratio %>",
    "<%= settings.arb_perps_minimum_initial_margin_ratio %>",
    "<%= settings.arb_perps_maintenance_margin_scalar %>",
    "<%= settings.arb_perps_flag_reward_ratio_d18 %>",
    "<%= settings.arb_perps_minimum_position_margin %>",
]

[invoke.setPerpsArbLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.arb_perps_market_id %>", "<%= settings.arb_perps_locked_oi_ratio %>"]
