[var.perps_gmx_market_settings]
gmx_perps_market_id = "2200"
gmx_perps_market_skew_scale = "<%= parseEther(String(250_000)) %>"
gmx_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
gmx_perps_maker_fee_ratio = "<%= parseEther('0.000200') %>"
gmx_perps_taker_fee_ratio = "<%= parseEther('0.001000') %>"
gmx_perps_max_market_size = "<%= parseEther(String(35_000)) %>"
gmx_perps_max_market_value = "<%= parseEther(String(500_000)) %>"
gmx_perps_initial_margin_ratio = "<%= parseEther('1.27') %>"
gmx_perps_maintenance_margin_scalar = "<%= parseEther('0.44') %>"
gmx_perps_minimum_initial_margin_ratio = "<%= parseEther('0.05') %>"
gmx_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
gmx_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
gmx_perps_max_seconds_in_liquidation_window = "30"
gmx_perps_minimum_position_margin = "<%= parseEther('50') %>"
gmx_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
gmx_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
gmx_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createGmxPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.gmx_perps_market_id %>", "GMX", "GMX"]

[invoke.setPerpsPriceGmx]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.gmx_perps_market_id %>",
    "<%= extras.gmx_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsGmxSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.gmx_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.gmx_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.gmx_pyth_settlement_strategy.arg = 2
[invoke.setPerpsGmxSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.gmx_perps_market_id %>",
    "<%= extras.gmx_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_gmx %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsGmxFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.gmx_perps_market_id %>",
    "<%= settings.gmx_perps_market_skew_scale %>",
    "<%= settings.gmx_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsGmxOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.gmx_perps_market_id %>",
    "<%= settings.gmx_perps_maker_fee_ratio %>",
    "<%= settings.gmx_perps_taker_fee_ratio %>",
]

[invoke.setPerpsGmxMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.gmx_perps_market_id %>", "<%= settings.gmx_perps_max_market_size %>"]

[invoke.setPerpsGmxMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.gmx_perps_market_id %>", "<%= settings.gmx_perps_max_market_value %>"]

[invoke.setPerpsGmxMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.gmx_perps_market_id %>",
    "<%= settings.gmx_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.gmx_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.gmx_perps_max_liquidation_pd %>",
    "<%= settings.gmx_perps_endorsed_liquidator %>",
]

[invoke.setPerpsGmxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.gmx_perps_market_id %>",
    "<%= settings.gmx_perps_initial_margin_ratio %>",
    "<%= settings.gmx_perps_minimum_initial_margin_ratio %>",
    "<%= settings.gmx_perps_maintenance_margin_scalar %>",
    "<%= settings.gmx_perps_flag_reward_ratio_d18 %>",
    "<%= settings.gmx_perps_minimum_position_margin %>",
]

[invoke.setPerpsGmxLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.gmx_perps_market_id %>", "<%= settings.gmx_perps_locked_oi_ratio %>"]
