[var.perps_safe_market_settings]
safe_perps_market_id = "8500"
safe_perps_market_skew_scale = "<%= parseEther(String(3_000_000)) %>"
safe_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
safe_perps_maker_fee_ratio = "<%= parseEther('0.000000') %>"
safe_perps_taker_fee_ratio = "<%= parseEther('0.000500') %>"
safe_perps_max_market_size = "<%= parseEther(String(500_000)) %>"
safe_perps_max_market_value = "<%= parseEther(String(500_000)) %>"
safe_perps_initial_margin_ratio = "<%= parseEther('1.211') %>"
safe_perps_maintenance_margin_scalar = "<%= parseEther('0.317') %>"
safe_perps_minimum_initial_margin_ratio = "<%= parseEther('0.05') %>"
safe_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
safe_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
safe_perps_max_seconds_in_liquidation_window = "30"
safe_perps_minimum_position_margin = "<%= parseEther('50') %>"
safe_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
safe_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
safe_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createSafePerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.safe_perps_market_id %>", "Safe", "SAFE"]

[invoke.setPerpsPriceSafe]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.safe_perps_market_id %>",
    "<%= extras.safe_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsSafeSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.safe_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.safe_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.safe_pyth_settlement_strategy.arg = 2
[invoke.setPerpsSafeSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.safe_perps_market_id %>",
    "<%= extras.safe_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_safe %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsSafeFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.safe_perps_market_id %>",
    "<%= settings.safe_perps_market_skew_scale %>",
    "<%= settings.safe_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsSafeOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.safe_perps_market_id %>",
    "<%= settings.safe_perps_maker_fee_ratio %>",
    "<%= settings.safe_perps_taker_fee_ratio %>",
]

[invoke.setPerpsSafeMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.safe_perps_market_id %>", "<%= settings.safe_perps_max_market_size %>"]

[invoke.setPerpsSafeMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.safe_perps_market_id %>", "<%= settings.safe_perps_max_market_value %>"]

[invoke.setPerpsSafeMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.safe_perps_market_id %>",
    "<%= settings.safe_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.safe_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.safe_perps_max_liquidation_pd %>",
    "<%= settings.safe_perps_endorsed_liquidator %>",
]

[invoke.setPerpsSafeLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.safe_perps_market_id %>",
    "<%= settings.safe_perps_initial_margin_ratio %>",
    "<%= settings.safe_perps_minimum_initial_margin_ratio %>",
    "<%= settings.safe_perps_maintenance_margin_scalar %>",
    "<%= settings.safe_perps_flag_reward_ratio_d18 %>",
    "<%= settings.safe_perps_minimum_position_margin %>",
]

[invoke.setPerpsSafeLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.safe_perps_market_id %>", "<%= settings.safe_perps_locked_oi_ratio %>"]
