[var.perps_stx_market_settings]
stx_perps_market_id = "3100"
stx_perps_market_skew_scale = "<%= parseEther(String(22_500_000)) %>"
stx_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
stx_perps_maker_fee_ratio = "<%= parseEther('0.000200') %>"
stx_perps_taker_fee_ratio = "<%= parseEther('0.001000') %>"
stx_perps_max_market_size = "<%= parseEther(String(849_150)) %>"
stx_perps_max_market_value = "<%= parseEther(String(1_000_000)) %>"
stx_perps_initial_margin_ratio = "<%= parseEther('2.61') %>"
stx_perps_maintenance_margin_scalar = "<%= parseEther('0.43') %>"
stx_perps_minimum_initial_margin_ratio = "<%= parseEther('0.05') %>"
stx_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
stx_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
stx_perps_max_seconds_in_liquidation_window = "30"
stx_perps_minimum_position_margin = "<%= parseEther('50') %>"
stx_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
stx_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
stx_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createStxPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.stx_perps_market_id %>", "Stacks", "STX"]

[invoke.setPerpsPriceStx]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.stx_perps_market_id %>",
    "<%= extras.stx_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsStxSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.stx_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.stx_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.stx_pyth_settlement_strategy.arg = 2
[invoke.setPerpsStxSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.stx_perps_market_id %>",
    "<%= extras.stx_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_stx %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsStxFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.stx_perps_market_id %>",
    "<%= settings.stx_perps_market_skew_scale %>",
    "<%= settings.stx_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsStxOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.stx_perps_market_id %>",
    "<%= settings.stx_perps_maker_fee_ratio %>",
    "<%= settings.stx_perps_taker_fee_ratio %>",
]

[invoke.setPerpsStxMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.stx_perps_market_id %>", "<%= settings.stx_perps_max_market_size %>"]

[invoke.setPerpsStxMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.stx_perps_market_id %>", "<%= settings.stx_perps_max_market_value %>"]

[invoke.setPerpsStxMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.stx_perps_market_id %>",
    "<%= settings.stx_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.stx_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.stx_perps_max_liquidation_pd %>",
    "<%= settings.stx_perps_endorsed_liquidator %>",
]

[invoke.setPerpsStxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.stx_perps_market_id %>",
    "<%= settings.stx_perps_initial_margin_ratio %>",
    "<%= settings.stx_perps_minimum_initial_margin_ratio %>",
    "<%= settings.stx_perps_maintenance_margin_scalar %>",
    "<%= settings.stx_perps_flag_reward_ratio_d18 %>",
    "<%= settings.stx_perps_minimum_position_margin %>",
]

[invoke.setPerpsStxLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.stx_perps_market_id %>", "<%= settings.stx_perps_locked_oi_ratio %>"]
