[var.perps_wif_market_settings]
wif_perps_market_id = "500"
wif_perps_market_skew_scale = "<%= parseEther(String(30_000_000)) %>"
wif_perps_market_max_funding_velocity = "<%= parseEther('9') %>"
wif_perps_maker_fee_ratio = "<%= parseEther('0.000200') %>"
wif_perps_taker_fee_ratio = "<%= parseEther('0.001000') %>"
wif_perps_max_market_size = "<%= parseEther(String(1_500_000)) %>"
wif_perps_max_market_value = "<%= parseEther(String(2_000_000)) %>"
wif_perps_initial_margin_ratio = "<%= parseEther('5.99') %>"
wif_perps_maintenance_margin_scalar = "<%= parseEther('0.4') %>"
wif_perps_minimum_initial_margin_ratio = "<%= parseEther('0.04') %>"
wif_perps_flag_reward_ratio_d18 = "<%= parseEther('0.0003') %>"
wif_perps_max_liquidation_limit_accumulation_multiplier = "<%= parseEther('1.5') %>"
wif_perps_max_seconds_in_liquidation_window = "30"
wif_perps_minimum_position_margin = "<%= parseEther('50') %>"
wif_perps_locked_oi_ratio = "<%= parseEther('0.5') %>"
wif_perps_max_liquidation_pd = "<%= parseEther('0.0005') %>"
wif_perps_endorsed_liquidator = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"

[invoke.createWifPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.wif_perps_market_id %>", "Wif", "WIF"]

[invoke.setPerpsPriceWif]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.wif_perps_market_id %>",
    "<%= extras.wif_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.addPerpsWifSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [

    "<%= settings.wif_perps_market_id %>",

    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.wif_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.wif_pyth_settlement_strategy.arg = 2
[invoke.setPerpsWifSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.wif_perps_market_id %>",
    "<%= extras.wif_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_wif %>", settlementReward = "<%= settings.settlement_reward %>", disabled = false, commitmentPriceDelay = "<%= settings.commitment_price_delay %>" },
]

[invoke.setPerpsWifFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.wif_perps_market_id %>",
    "<%= settings.wif_perps_market_skew_scale %>",
    "<%= settings.wif_perps_market_max_funding_velocity %>",
]

[invoke.setPerpsWifOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.wif_perps_market_id %>",
    "<%= settings.wif_perps_maker_fee_ratio %>",
    "<%= settings.wif_perps_taker_fee_ratio %>",
]

[invoke.setPerpsWifMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = ["<%= settings.wif_perps_market_id %>", "<%= settings.wif_perps_max_market_size %>"]

[invoke.setPerpsWifMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = ["<%= settings.wif_perps_market_id %>", "<%= settings.wif_perps_max_market_value %>"]

[invoke.setPerpsWifMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.wif_perps_market_id %>",
    "<%= settings.wif_perps_max_liquidation_limit_accumulation_multiplier %>",
    "<%= settings.wif_perps_max_seconds_in_liquidation_window %>",
    "<%= settings.wif_perps_max_liquidation_pd %>",
    "<%= settings.wif_perps_endorsed_liquidator %>",
]

[invoke.setPerpsWifLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.wif_perps_market_id %>",
    "<%= settings.wif_perps_initial_margin_ratio %>",
    "<%= settings.wif_perps_minimum_initial_margin_ratio %>",
    "<%= settings.wif_perps_maintenance_margin_scalar %>",
    "<%= settings.wif_perps_flag_reward_ratio_d18 %>",
    "<%= settings.wif_perps_minimum_position_margin %>",
]

[invoke.setPerpsWifLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = ["<%= settings.wif_perps_market_id %>", "<%= settings.wif_perps_locked_oi_ratio %>"]
