[setting.stata_usdc_address]

[invoke.configure_sstatausdc_collateral]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"  # "args" see below in the multiline block

[[invoke.configure_sstatausdc_collateral.args]]
tokenAddress = "<%= extras.synth_usdc_token_address %>"
oracleNodeId = "<%= extras.erc_4626_to_assets_ratio_oracle_id %>"
issuanceRatioD18 = "<%= settings.sstatausdc_issuance_ratio %>"
liquidationRatioD18 = "<%= settings.sstatausdc_liquidation_ratio %>"
liquidationRewardD18 = "<%= settings.sstatausdc_liquidation_reward %>"
minDelegationD18 = "<%= settings.sstatausdc_min_delegation %>"
depositingEnabled = true
