[setting.pythAlgoFeedId]
defaultValue = "0xfa17ceaf30d19ba51112fdcc750cc83454776f47fb0112e4af07f15f4bb1ebc0"

[setting.perpsAlgoMarketId]
defaultValue = "3500"

[setting.perpsAlgoSkewScale]
defaultValue = "<%= String(51_937_500) %>"

[setting.perpsAlgoMaxFundingVelocity]
defaultValue = "36"

[setting.perpsAlgoMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsAlgoTakerFeeRatio]
defaultValue = "0.0010"

[setting.perpsAlgoMaxMarketSize]
defaultValue = "<%= String(536_900) %>"

[setting.perpsAlgoMaxMarketValue]
defaultValue = "<%= String(50_000) %>"

[setting.perpsAlgoInitialMarginRatio]
defaultValue = "5.19"

[setting.perpsAlgoMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsAlgoMaintenanceMarginScalar]
defaultValue = "0.36"

[setting.perpsAlgoFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsAlgoMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsAlgoMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsAlgoMinimumPositionMargin]
defaultValue = "50"

[setting.perpsAlgoLockedOiRatio]
defaultValue = "0.5"

[setting.perpsAlgoSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsAlgoMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsAlgoEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
