[setting.pythAtomFeedId]
defaultValue = "0xb00b60f88b03a6a625a8d1c048c3f66653edf217439983d037e7222c4e612819"

[setting.perpsAtomMarketId]
defaultValue = "3700"

[setting.perpsAtomSkewScale]
defaultValue = "<%= String(5_625_000) %>"

[setting.perpsAtomMaxFundingVelocity]
defaultValue = "36"

[setting.perpsAtomMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsAtomTakerFeeRatio]
defaultValue = "0.0010"

[setting.perpsAtomMaxMarketSize]
defaultValue = "<%= String(11_736) %>"

[setting.perpsAtomMaxMarketValue]
defaultValue = "<%= String(50_000) %>"

[setting.perpsAtomInitialMarginRatio]
defaultValue = "2.49"

[setting.perpsAtomMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsAtomMaintenanceMarginScalar]
defaultValue = "0.31"

[setting.perpsAtomFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsAtomMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsAtomMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsAtomMinimumPositionMargin]
defaultValue = "50"

[setting.perpsAtomLockedOiRatio]
defaultValue = "0.5"

[setting.perpsAtomSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsAtomMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsAtomEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
