[setting.pythDotFeedId]
defaultValue = "0xca3eed9b267293f6595901c734c7525ce8ef49adafe8284606ceb307afa2ca5b"

[setting.perpsDotMarketId]
defaultValue = "4400"

[setting.perpsDotSkewScale]
defaultValue = "<%= String(7_500_000) %>"

[setting.perpsDotMaxFundingVelocity]
defaultValue = "36"

[setting.perpsDotMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsDotTakerFeeRatio]
defaultValue = "0.0010"

[setting.perpsDotMaxMarketSize]
defaultValue = "<%= String(13_851) %>"

[setting.perpsDotMaxMarketValue]
defaultValue = "<%= String(50_000) %>"

[setting.perpsDotInitialMarginRatio]
defaultValue = "2.09"

[setting.perpsDotMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsDotMaintenanceMarginScalar]
defaultValue = "0.32"

[setting.perpsDotFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsDotMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsDotMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsDotMinimumPositionMargin]
defaultValue = "50"

[setting.perpsDotLockedOiRatio]
defaultValue = "0.5"

[setting.perpsDotSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsDotMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsDotEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
