[setting.pythEosFeedId]
defaultValue = "0x06ade621dbc31ed0fc9255caaab984a468abe84164fb2ccc76f02a4636d97e31"

[setting.perpsEosMarketId]
defaultValue = "4600"

[setting.perpsEosSkewScale]
defaultValue = "<%= String(48_000_000) %>"

[setting.perpsEosMaxFundingVelocity]
defaultValue = "36"

[setting.perpsEosMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsEosTakerFeeRatio]
defaultValue = "0.0010"

[setting.perpsEosMaxMarketSize]
defaultValue = "<%= String(123_193) %>"

[setting.perpsEosMaxMarketValue]
defaultValue = "<%= String(50_000) %>"

[setting.perpsEosInitialMarginRatio]
defaultValue = "2.47"

[setting.perpsEosMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsEosMaintenanceMarginScalar]
defaultValue = "0.33"

[setting.perpsEosFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsEosMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsEosMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsEosMinimumPositionMargin]
defaultValue = "50"

[setting.perpsEosLockedOiRatio]
defaultValue = "0.5"

[setting.perpsEosSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsEosMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsEosEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
