[setting.pythGrtFeedId]
defaultValue = "0x4d1f8dae0d96236fb98e8f47471a366ec3b1732b47041781934ca3a9bb2f35e7"

[setting.perpsGrtMarketId]
defaultValue = "5200"

[setting.perpsGrtSkewScale]
defaultValue = "<%= String(75_000_000) %>"

[setting.perpsGrtMaxFundingVelocity]
defaultValue = "36"

[setting.perpsGrtMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsGrtTakerFeeRatio]
defaultValue = "0.0010"

[setting.perpsGrtMaxMarketSize]
defaultValue = "<%= String(332_170) %>"

[setting.perpsGrtMaxMarketValue]
defaultValue = "<%= String(50_000) %>"

[setting.perpsGrtInitialMarginRatio]
defaultValue = "4.22"

[setting.perpsGrtMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsGrtMaintenanceMarginScalar]
defaultValue = "0.39"

[setting.perpsGrtFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsGrtMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsGrtMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsGrtMinimumPositionMargin]
defaultValue = "50"

[setting.perpsGrtLockedOiRatio]
defaultValue = "0.5"

[setting.perpsGrtSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsGrtMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsGrtEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
