[setting.pythJtoFeedId]
defaultValue = "0xb43660a5f790c69354b0729a5ef9d50d68f1df92107540210b9cccba1f947cc2"

[setting.perpsJtoMarketId]
defaultValue = "5500"

[setting.perpsJtoSkewScale]
defaultValue = "<%= String(4_000_000) %>"

[setting.perpsJtoMaxFundingVelocity]
defaultValue = "36"

[setting.perpsJtoMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsJtoTakerFeeRatio]
defaultValue = "0.0010"

[setting.perpsJtoMaxMarketSize]
defaultValue = "<%= String(27_247) %>"

[setting.perpsJtoMaxMarketValue]
defaultValue = "<%= String(50_000) %>"

[setting.perpsJtoInitialMarginRatio]
defaultValue = "1.49"

[setting.perpsJtoMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsJtoMaintenanceMarginScalar]
defaultValue = "0.38"

[setting.perpsJtoFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsJtoMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsJtoMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsJtoMinimumPositionMargin]
defaultValue = "50"

[setting.perpsJtoLockedOiRatio]
defaultValue = "0.5"

[setting.perpsJtoSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsJtoMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsJtoEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
