[setting.pythOpFeedId]
defaultValue = "0x385f64d993f7b77d8182ed5003d97c60aa3361f3cecfe711544d2d59165e9bdf"

[setting.perpsOpMarketId]
defaultValue = "1000"

[setting.perpsOpSkewScale]
defaultValue = "<%= String(16_000_000) %>"

[setting.perpsOpMaxFundingVelocity]
defaultValue = "36"

[setting.perpsOpMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsOpTakerFeeRatio]
defaultValue = "0.0010"

[setting.perpsOpMaxMarketSize]
defaultValue = "<%= String(500_000) %>"

[setting.perpsOpMaxMarketValue]
defaultValue = "<%= String(1_500_000) %>"

[setting.perpsOpInitialMarginRatio]
defaultValue = "2.27"

[setting.perpsOpMinimumInitialMarginRatio]
defaultValue = "0.04"

[setting.perpsOpMaintenanceMarginScalar]
defaultValue = "0.38"

[setting.perpsOpFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsOpMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsOpMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsOpMinimumPositionMargin]
defaultValue = "50"

[setting.perpsOpLockedOiRatio]
defaultValue = "0.5"

[setting.perpsOpSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsOpMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsOpEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
