[setting.pythPythFeedId]
defaultValue = "0x0bbf28e9a841a1cc788f6a361b17ca072d0ea3098a1e5df1c3922d06719579ff"

[setting.perpsPythMarketId]
defaultValue = "6200"

[setting.perpsPythSkewScale]
defaultValue = "<%= String(14_437_500) %>"

[setting.perpsPythMaxFundingVelocity]
defaultValue = "36"

[setting.perpsPythMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsPythTakerFeeRatio]
defaultValue = "0.0010"

[setting.perpsPythMaxMarketSize]
defaultValue = "<%= String(224_807) %>"

[setting.perpsPythMaxMarketValue]
defaultValue = "<%= String(50_000) %>"

[setting.perpsPythInitialMarginRatio]
defaultValue = "0.84"

[setting.perpsPythMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsPythMaintenanceMarginScalar]
defaultValue = "0.37"

[setting.perpsPythFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsPythMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsPythMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsPythMinimumPositionMargin]
defaultValue = "50"

[setting.perpsPythLockedOiRatio]
defaultValue = "0.5"

[setting.perpsPythSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsPythMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsPythEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
