[setting.referrerFee]
defaultValue = "<%= parseEther('0.2') %>"

[invoke.setPolynomialAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = ["0x159c143eF9Be79d5672726150462C9EfA679b27c", "<%= settings.referrerFee %>"]

[invoke.setKwentaAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = ["0x3bD64247d879AF879e6f6e62F81430186391Bdb8", "<%= settings.referrerFee %>"]

[invoke.setParifiAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = ["0x32A74B2cE1a0783A182f607D29207e571a1cDD4D", "<%= settings.referrerFee %>"]

[invoke.setMassDotMoneyAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = ["0xf944069B489F1ebfF4C3C6a6014d58cBEf7C7009", "<%= settings.referrerFee %>"]

[invoke.setInfinexAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = ["0x24f5A599a40730dc0475eCE8dD41C4D3A4Ba4Bf3", "<%= settings.referrerFee %>"]

[invoke.setSynthetixAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = ["0xebAC8Fc8752A267A36cE683A867000F69Fd0e73d", "<%= settings.referrerFee %>"]

[invoke.setCyberDEXAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = ["0x829d7E022c2ACD05a875bCa4Bd11F56E003B727B", "<%= settings.referrerFee %>"]
