[setting.pythShibFeedId]
defaultValue = "0xf0d57deca57b3da2fe63a493f4c25925fdfd8edf834b20f93e1f84dbd1504d4a"

[setting.perpsShibMarketId]
defaultValue = "6500"

[setting.perpsShibSkewScale]
defaultValue = "<%= String(1_875_000_000_000) %>"

[setting.perpsShibMaxFundingVelocity]
defaultValue = "36"

[setting.perpsShibMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsShibTakerFeeRatio]
defaultValue = "0.0010"

[setting.perpsShibMaxMarketSize]
defaultValue = "<%= String(4_100_461_301) %>"

[setting.perpsShibMaxMarketValue]
defaultValue = "<%= String(50_000) %>"

[setting.perpsShibInitialMarginRatio]
defaultValue = "2.2"

[setting.perpsShibMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsShibMaintenanceMarginScalar]
defaultValue = "0.32"

[setting.perpsShibFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsShibMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsShibMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsShibMinimumPositionMargin]
defaultValue = "50"

[setting.perpsShibLockedOiRatio]
defaultValue = "0.5"

[setting.perpsShibSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsShibMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsShibEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
