[setting.pythUniFeedId]
defaultValue = "0x78d185a741d07edb3412b09008b7c5cfb9bbbd7d568bf00ba737b456ba171501"

[setting.perpsUniMarketId]
defaultValue = "6900"

[setting.perpsUniSkewScale]
defaultValue = "<%= String(2_250_000) %>"

[setting.perpsUniMaxFundingVelocity]
defaultValue = "36"

[setting.perpsUniMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsUniTakerFeeRatio]
defaultValue = "0.0010"

[setting.perpsUniMaxMarketSize]
defaultValue = "<%= String(8_753) %>"

[setting.perpsUniMaxMarketValue]
defaultValue = "<%= String(50_000) %>"

[setting.perpsUniInitialMarginRatio]
defaultValue = "0.77"

[setting.perpsUniMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsUniMaintenanceMarginScalar]
defaultValue = "0.31"

[setting.perpsUniFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsUniMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsUniMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsUniMinimumPositionMargin]
defaultValue = "50"

[setting.perpsUniLockedOiRatio]
defaultValue = "0.5"

[setting.perpsUniSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsUniMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsUniEndorsedLiquidator]
defaultValue = "0x11233749514Ab8d00C0A5873DF7428b3db70030f"
