[var.sol_spot_settings]
synth_sol_max_collateral_amount = "<%= parseEther(String(7_500)) %>"
synth_sol_skew_scale = "<%= parseEther(String(1_406_250)) %>"

[invoke.SpotMarketProxy_createSynth_sol]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "owner"
func = "createSynth"
args = ["Synthetic Wormhole SOL", "swSOL", "<%= settings.pdao %>"]
extra.synth_sol_market_id.event = "SynthRegistered"
extra.synth_sol_market_id.arg = 0
extra.synth_sol_token_address.event = "SynthRegistered"
extra.synth_sol_token_address.arg = 1

[invoke.SpotMarketProxy_updatePriceData_sol]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_sol_market_id %>"]
func = "updatePriceData"
args = [
    "<%= extras.synth_sol_market_id %>",
    "<%= extras.sol_oracle_id %>",
    "<%= extras.sol_oracle_id %>",
    "<%= settings.strict_staleness_tolerance %>",
]

[invoke.CoreProxy_configureMaximumMarketCollateral_sol]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= extras.synth_sol_market_id %>",
    "<%= settings.sol_address %>",
    "<%= settings.synth_sol_max_collateral_amount %>",
]

[invoke.SpotMarketProxy_setMarketSkewScale_sol]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_sol_market_id %>"]
func = "setMarketSkewScale"
args = ["<%= extras.synth_sol_market_id %>", "<%= settings.synth_sol_skew_scale %>"]

[invoke.SpotMarketProxy_setWrapper_sol]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_sol_market_id %>"]
func = "setWrapper"
args = [
    "<%= extras.synth_sol_market_id %>",
    "<%= settings.sol_address %>",
    "<%= settings.synth_sol_max_collateral_amount %>",
]

[invoke.SpotMarketProxy_addSettlementStrategy_sol]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_sol_market_id %>"]
func = "addSettlementStrategy"
args = [
    "<%= extras.synth_sol_market_id %>",
    { strategyType = "1", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", url = "", settlementReward = 0, minimumUsdExchangeAmount = "0", maxRoundingLoss = "1", priceDeviationTolerance = "0", disabled = false },
]
extra.synth_sol_settlement_strategy_id.event = "SettlementStrategyAdded"
extra.synth_sol_settlement_strategy_id.arg = 1

[invoke.SpotMarketProxy_setSettlementStrategy_sol]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_sol_market_id %>"]
func = "setSettlementStrategy"
args = [
    "<%= extras.synth_sol_market_id %>",
    "<%= extras.synth_sol_settlement_strategy_id %>",
    { strategyType = "1", settlementDelay = "<%= settings.settlement_delay %>", settlementWindowDuration = "<%= settings.settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_sol %>", url = "<%= settings.pyth_feed_url %>", settlementReward = "<%= settings.settlement_reward %>", minimumUsdExchangeAmount = "<%= settings.settlement_minimum_usd_exchange_amount %>", maxRoundingLoss = "<%= settings.settlement_max_rounding_loss %>", priceDeviationTolerance = "<%= settings.price_deviation_tolerance %>", disabled = true },
]

[invoke.SpotMarketProxy_setAtomicFixedFee_sol]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_sol_market_id %>"]
func = "setAtomicFixedFee"
args = ["<%= extras.synth_sol_market_id %>", "<%= parseEther(String(0.30)) %>"]

[invoke.SpotMarketProxy_setCollateralLeverage_sol]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_sol_market_id %>"]
func = "setCollateralLeverage"
args = ["<%= extras.synth_sol_market_id %>", "<%= parseEther('10') %>"]
