[clone.erc_4626_to_assets_ratio_oracle]
source = "erc-4626-to-assets-ratio-oracle"
var.vault = "<%= settings.stata_usdc_address %>" # On testnet, we provide no vault here and use the mocks deployed by this package

[invoke.register_erc_4626_to_assets_ratio_oracle_node]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    2, # 2 = external node
    "<%= defaultAbiCoder.encode(['address'], [imports.erc_4626_to_assets_ratio_oracle.contracts.ERC4626ToAssetsRatioOracle.address]) %>",
    [
    ],
]
extra.erc_4626_to_assets_ratio_oracle_id.event = "NodeRegistered"
extra.erc_4626_to_assets_ratio_oracle_id.arg = 0
