[var.perps_collateral_sUSDe_settings]
sUSDe_upper_limit_discount = "<%= parseEther('0.0051') %>"
sUSDe_lower_limit_discount = "<%= parseEther('0.0050') %>"
sUSDe_discount_scalar = "<%= 1 %>"                         #1 wei

[invoke.PerpsMarketProxy_setCollateralConfiguration_sUSDe]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setCollateralConfiguration"
args = [
    "<%= extras.synth_USDe_market_id %>",
    "<%= settings.synth_USDe_max_collateral_amount %>",
    "<%= settings.sUSDe_upper_limit_discount %>",
    "<%= settings.sUSDe_lower_limit_discount %>",
    "<%= settings.sUSDe_discount_scalar %>",
]

[invoke.CoreProxy_configureMaximumMarketCollateral_Perps_sUSDe]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= imports.perpsFactory.extras.superMarketId %>",
    "<%= extras.synth_USDe_token_address %>",
    "<%= settings.synth_USDe_max_collateral_amount %>",
]
