[invoke.enable_feature_createAccount]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('createAccount') %>", true]

[invoke.enable_feature_deposit]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('deposit') %>", false]

[invoke.enable_feature_withdraw]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('withdraw') %>", true]

[invoke.enable_feature_mintUsd]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('mintUsd') %>", false]

[invoke.enable_feature_burnUsd]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('burnUsd') %>", false]

[invoke.enable_feature_liquidate]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('liquidate') %>", false]

[invoke.enable_feature_liquidateVault]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('liquidateVault') %>", false]

[invoke.enable_feature_depositMarketCollateral]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('depositMarketCollateral') %>", false]

[invoke.enable_feature_withdrawMarketCollateral]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('withdrawMarketCollateral') %>", false]

[invoke.enable_feature_depositMarketUsd]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('depositMarketUsd') %>", false]

[invoke.enable_feature_withdrawMarketUsd]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('withdrawMarketUsd') %>", false]

[invoke.enable_feature_claimRewards]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('claimRewards') %>", false]

[invoke.enable_feature_delegateCollateral]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = ["<%= formatBytes32String('delegateCollateral') %>", true]
