[var.perps_global_settings]
perps_liquidation_min_keeper_reward_usd = "1"
perps_liquidation_min_keeper_profit_ratio_d18 = "0.30"
perps_liquidation_max_keeper_reward_usd = "30"
perps_liquidation_max_keeper_scaling_ratio_d18 = "0.0003"
perps_low_util_gradient = "0"
perps_gradient_breakpoint = "0"
perps_high_util_gradient = "0"
perps_collateral_liquidation_ratio = "0.0003"
perps_max_positions_per_account = "10"
perps_max_collaterals_per_account = "3"

[invoke.setPerpsLiquidationRewardGuards]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setKeeperRewardGuards"
args = [
    "<%= parseEther(settings.perps_liquidation_min_keeper_reward_usd) %>",
    "<%= parseEther(settings.perps_liquidation_min_keeper_profit_ratio_d18) %>",
    "<%= parseEther(settings.perps_liquidation_max_keeper_reward_usd) %>",
    "<%= parseEther(settings.perps_liquidation_max_keeper_scaling_ratio_d18) %>",
]
depends = ['provision.perpsFactory', 'var.perps_global_settings']

[invoke.setPerAccountCapsPerps]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setPerAccountCaps"
args = [
    "<%= settings.perps_max_positions_per_account %>",
    "<%= settings.perps_max_collaterals_per_account %>",
]

# [invoke.setPerpsMarketKeeperCostNodeId]
# target = ["perpsFactory.PerpsMarketProxy"]
# fromCall.func = "owner"
# func = "updateKeeperCostNodeId"
# args = ["<%= extras.perps_keeper_cost_usd_oracle_id %>"]

[invoke.setInterestRateParams]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setInterestRateParameters"
args = [
    "<%= parseEther(settings.perps_low_util_gradient) %>",
    "<%= parseEther(settings.perps_gradient_breakpoint) %>",
    "<%= parseEther(settings.perps_high_util_gradient) %>",
]
depends = ['provision.perpsFactory', 'var.perps_global_settings']

[invoke.PerpsMarketProxy_setCollateralLiquidationRatio_btc]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setCollateralLiquidateRewardRatio"
args = ["<%= parseEther(settings.perps_collateral_liquidation_ratio) %>"]
depends = ['var.perps_global_settings']
