[setting.referrer_fee]
defaultValue = "<%= parseEther('0.2') %>"

[invoke.setPolynomialAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = ["0x159c143eF9Be79d5672726150462C9EfA679b27c", "<%= settings.referrer_fee %>"]

[invoke.setKwentaAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = ["0xFffe627790EF1B28E3b48000b8Ba964b55766fF8", "<%= settings.referrer_fee %>"]

[invoke.setInfinexAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = ["0xa7DB9b0a95D253022068d43BD1d64756f92eF83C", "<%= settings.referrer_fee %>"]

[invoke.setSynthetixAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = ["0xd25215758734dd3ade497ce04de1c35820964126", "<%= settings.referrer_fee %>"]

[invoke.setCyberDEXAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = ["0x829d7E022c2ACD05a875bCa4Bd11F56E003B727B", "<%= settings.referrer_fee %>"]
