# This registers a staleness node that looks to Pyth for a fresh enough price, or otherwise reverts with an ERC-7412 compatible error
# Latest Pyth Price
[invoke.registerPythCompOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    5, # 5 = pyth aggregator type
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.pyth_feed_id_comp, false]) %>",
    [
    ],
]
extra.comp_pyth_oracle_id.event = "NodeRegistered"
extra.comp_pyth_oracle_id.arg = 0
# Pyth Off-chain Lookup
[invoke.registerLookupCompOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    9, # 9 = PythOffchainLookupNode
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.pyth_feed_id_comp, settings.default_staleness_tolerance]) %>",
    [
    ],
]
extra.comp_lookup_oracle_id.event = "NodeRegistered"
extra.comp_lookup_oracle_id.arg = 0
# Staleness Node
[invoke.registerCompOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    7, # 7 = staleness circuit breaker
    "<%= defaultAbiCoder.encode(['uint256'], [settings.default_staleness_tolerance]) %>",
    [
        "<%= extras.comp_pyth_oracle_id %>",
        "<%= extras.comp_lookup_oracle_id %>",
    ],
]
extra.comp_oracle_id.event = "NodeRegistered"
extra.comp_oracle_id.arg = 0
