name: e2e

on:
  # pull_request: {}
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
    strategy:
      fail-fast: false
      matrix:
        toml:
          - "omnibus-mainnet.toml"
          - "omnibus-optimism-mainnet.toml"
          - "omnibus-goerli.toml"
          - "omnibus-optimism-goerli.toml"
          - "omnibus-base-goerli-andromeda.toml"

        include:
          - toml: "omnibus-mainnet.toml"
            chainId: 1
            providerUrl: "https://mainnet.infura.io/v3/$INFURA_API_KEY"

          - toml: "omnibus-optimism-mainnet.toml"
            chainId: 10
            providerUrl: "https://optimism-mainnet.infura.io/v3/$INFURA_API_KEY"

          - toml: "omnibus-goerli.toml"
            chainId: 5
            providerUrl: "https://goerli.infura.io/v3/$INFURA_API_KEY"

          - toml: "omnibus-optimism-goerli.toml"
            chainId: 420
            providerUrl: "https://optimism-goerli.infura.io/v3/$INFURA_API_KEY"

          - toml: "omnibus-base-goerli-andromeda.toml"
            chainId: 84531
            providerUrl: "https://base-goerli.infura.io/v3/$INFURA_API_KEY"

    steps:
      - name: Install Foundry (Cannon)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: anvil -V
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn --version
      - run: yarn install --immutable
      - run: yarn build ${{ matrix.chainId }} ${{ matrix.toml }}
      - name: "Tests"
        run: |
          echo "Run anvil"
          anvil --fork-url ${{ matrix.providerUrl }} &

          echo "Wait for anvil 127.0.0.1:8545"
          wget -q -O - --retry-connrefused --waitretry=20 --read-timeout=20 --timeout=15 -t 10 --post-data='{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"}' --header='Content-Type:application/json' http://127.0.0.1:8545

          echo "Execute tests"
          TEST_TOML="${{ matrix.toml }}" yarn test e2e/tests/${{ matrix.toml }}/*.e2e.js
